#!/usr/bin/env python3
"""
批量补充剩余高频真实命令，目标是将各主要领域覆盖得更全面。
本脚本只写入新的 YAML 文件，不破坏现有文件中的注释。
"""
import sys
import os
from pathlib import Path
from ruamel.yaml import YAML

yaml = YAML()
yaml.preserve_quotes = True
yaml.default_flow_style = False

DATA_DIR = Path("data")
META_PATH = DATA_DIR / "metadata.yaml"


def opt(flag_desc: str) -> dict:
    """将 'FLAG DESCRIPTION' 拆分为 option dict。"""
    parts = flag_desc.split(" ", 1)
    return {"flag": parts[0], "description": parts[1] if len(parts) > 1 else ""}


def ex(cmd: str, desc: str) -> dict:
    return {"command": cmd, "description": desc}


def make_cmd(
    name: str,
    desc: str,
    category: str,
    usage: str = None,
    options: list = None,
    examples: list = None,
    related: list = None,
    install_required: bool = False,
    install_method: str = None,
    platforms: list = None,
    risk: str = "low",
    risk_desc: str = None,
) -> dict:
    if usage is None:
        usage = f"{name} [OPTIONS] [ARGS]"
    if options is None:
        options = ["--help 显示帮助信息", "--version 显示版本信息"]
    if examples is None:
        examples = [
            [f"{name} --help", "查看帮助"],
            [f"{name} --version", "查看版本"],
        ]
    if platforms is None:
        platforms = ["linux", "darwin"]
    if related is None:
        related = []
    cmd = {
        "name": name,
        "category": category,
        "install_required": install_required,
        "description": desc,
        "usage": [usage],
        "options": [opt(o) for o in options],
        "examples": [ex(e[0], e[1]) for e in examples],
        "platforms": platforms,
        "related_commands": related,
    }
    if install_required and install_method:
        cmd["install_method"] = install_method
    if risk in ("medium", "high", "critical"):
        if risk_desc is None:
            risk_desc = "操作前请确认参数、目标环境和影响范围，建议在测试环境先行验证。"
        cmd["risks"] = [{"level": risk, "description": risk_desc}]
    return cmd


BATCH = {
    "os/linux-extra.yaml": {
        "category": "操作系统/Linux扩展命令",
        "description": "Linux 常用系统、文件、用户、磁盘、定时任务等扩展命令",
        "commands": [
            make_cmd("mkdir", "创建目录", "操作系统/Linux扩展命令",
                     usage="mkdir [OPTIONS] DIRECTORY...",
                     options=["-p 递归创建父目录", "-v 显示创建过程", "-m 设置权限模式"],
                     examples=[["mkdir -p /tmp/a/b", "递归创建目录"], ["mkdir -m 700 mydir", "创建权限为 700 的目录"]],
                     related=["rmdir", "cd"], risk="low"),
            make_cmd("touch", "更新文件时间戳或创建空文件", "操作系统/Linux扩展命令",
                     options=["-a 只更新访问时间", "-m 只更新修改时间", "-c 不创建新文件"],
                     examples=[["touch file.txt", "创建或更新 file.txt 时间戳"], ["touch -t 202401011200 file.txt", "设置指定时间"]],
                     related=["mkdir", "ls"], risk="low"),
            make_cmd("ln", "创建文件链接", "操作系统/Linux扩展命令",
                     usage="ln [OPTIONS] TARGET [LINK_NAME]",
                     options=["-s 创建符号链接", "-f 强制覆盖", "-v 显示过程"],
                     examples=[["ln -s /path/to/file link", "创建符号链接"], ["ln file hardlink", "创建硬链接"]],
                     related=["cp", "mv"], risk="medium", risk_desc="覆盖或错误的符号链接可能影响依赖路径，请确认目标"),
            make_cmd("chmod", "修改文件或目录权限", "操作系统/Linux扩展命令",
                     usage="chmod [OPTIONS] MODE FILE...",
                     options=["-R 递归修改", "-v 显示修改过程", "--reference 参考其他文件权限"],
                     examples=[["chmod 755 script.sh", "设置文件权限为 rwxr-xr-x"], ["chmod -R u+w dir", "递归添加用户写权限"]],
                     related=["chown", "umask"], risk="high", risk_desc="错误的权限设置可能导致服务无法访问或安全暴露"),
            make_cmd("chown", "修改文件或目录所有者", "操作系统/Linux扩展命令",
                     usage="chown [OPTIONS] [OWNER][:[GROUP]] FILE...",
                     options=["-R 递归修改", "--reference 参考其他文件所有者"],
                     examples=[["sudo chown user:group file.txt", "修改所有者和组"], ["sudo chown -R www-data: /var/www", "递归修改目录所有者"]],
                     related=["chmod", "useradd"], risk="high", risk_desc="更改系统目录所有者可能影响服务运行，请谨慎使用 -R"),
            make_cmd("umask", "显示或设置默认文件权限掩码", "操作系统/Linux扩展命令",
                     options=["-S 以符号方式显示"],
                     examples=[["umask", "显示当前 umask"], ["umask 027", "设置新文件默认权限掩码"]],
                     related=["chmod", "mkdir"], risk="medium", risk_desc="umask 设置过大会让新建文件权限过宽，建议按需配置"),
            make_cmd("mount", "挂载文件系统", "操作系统/Linux扩展命令",
                     usage="mount [OPTIONS] [DEVICE] [DIRECTORY]",
                     options=["-t 指定文件系统类型", "-o 指定挂载选项", "-a 挂载 /etc/fstab 中所有设备"],
                     examples=[["sudo mount /dev/sdb1 /mnt", "挂载分区到 /mnt"], ["sudo mount -a", "挂载 /etc/fstab 中定义的所有设备"]],
                     related=["umount", "lsblk"], risk="high", risk_desc="挂载到错误目录会覆盖现有数据，请确认目标目录为空或已备份"),
            make_cmd("umount", "卸载文件系统", "操作系统/Linux扩展命令",
                     usage="umount [OPTIONS] TARGET",
                     options=["-l 懒卸载", "-f 强制卸载", "-r 失败时以只读重新挂载"],
                     examples=[["sudo umount /mnt", "卸载 /mnt"], ["sudo umount -l /mnt", "懒卸载（允许进程退出后完全释放）"]],
                     related=["mount", "lsof"], risk="high", risk_desc="卸载时若有进程占用会导致失败或数据不一致，请先确认无活跃访问"),
            make_cmd("fdisk", "磁盘分区表管理工具", "操作系统/Linux扩展命令",
                     usage="fdisk [OPTIONS] DEVICE",
                     options=["-l 列出分区表", "-n 创建新分区", "-d 删除分区"],
                     examples=[["sudo fdisk -l", "列出所有磁盘分区"], ["sudo fdisk /dev/sdb", "进入交互式分区管理"]],
                     related=["parted", "lsblk"], risk="critical", risk_desc="修改分区表会破坏数据，操作前务必备份并确认磁盘"),
            make_cmd("parted", "高级磁盘分区工具", "操作系统/Linux扩展命令",
                     usage="parted [OPTIONS] [DEVICE] [COMMAND]",
                     options=["-l 列出分区", "mklabel 创建分区表", "mkpart 创建分区"],
                     examples=[["sudo parted -l", "列出所有分区"], ["sudo parted /dev/sdb mklabel gpt", "创建 GPT 分区表"]],
                     related=["fdisk", "mkfs"], risk="critical", risk_desc="分区操作会清除数据，请确认目标磁盘并已备份"),
            make_cmd("lsblk", "列出块设备信息", "操作系统/Linux扩展命令",
                     options=["-f 显示文件系统", "-m 显示权限信息", "-o 指定输出列"],
                     examples=[["lsblk", "列出块设备树"], ["lsblk -f", "显示文件系统和 UUID"]],
                     related=["df", "fdisk"], risk="low"),
            make_cmd("blkid", "显示块设备属性（UUID、文件系统类型等）", "操作系统/Linux扩展命令",
                     options=["-o 指定输出格式", "-s 指定显示字段", "-p 绕过缓存"],
                     examples=[["sudo blkid", "列出所有块设备 UUID"], ["sudo blkid /dev/sda1", "查看指定分区属性"]],
                     related=["lsblk", "mount"], risk="low"),
            make_cmd("useradd", "创建用户账户", "操作系统/Linux扩展命令",
                     usage="useradd [OPTIONS] LOGIN",
                     options=["-m 创建主目录", "-s 指定登录 shell", "-G 指定附加组"],
                     examples=[["sudo useradd -m -s /bin/bash alice", "创建用户并生成主目录"], ["sudo useradd -G sudo,adm bob", "创建用户并加入附加组"]],
                     related=["usermod", "passwd"], risk="medium", risk_desc="创建系统用户可能影响权限策略，请确认 UID/GID 范围"),
            make_cmd("usermod", "修改用户账户", "操作系统/Linux扩展命令",
                     usage="usermod [OPTIONS] LOGIN",
                     options=["-aG 添加附加组", "-s 修改登录 shell", "-L 锁定用户"],
                     examples=[["sudo usermod -aG docker alice", "将用户加入 docker 组"], ["sudo usermod -L alice", "锁定用户账户"]],
                     related=["useradd", "passwd"], risk="medium", risk_desc="修改用户组或锁定账户可能导致无法登录，请谨慎操作"),
            make_cmd("userdel", "删除用户账户", "操作系统/Linux扩展命令",
                     usage="userdel [OPTIONS] LOGIN",
                     options=["-r 同时删除主目录和邮件池", "-f 强制删除"],
                     examples=[["sudo userdel alice", "删除用户"], ["sudo userdel -r alice", "删除用户及其主目录"]],
                     related=["useradd", "usermod"], risk="high", risk_desc="删除用户及其主目录会丢失数据，请确认无重要文件"),
            make_cmd("groupadd", "创建用户组", "操作系统/Linux扩展命令",
                     options=["-g 指定 GID", "-r 创建系统组"],
                     examples=[["sudo groupadd developers", "创建 developers 组"], ["sudo groupadd -g 1001 ops", "创建指定 GID 的组"]],
                     related=["groupdel", "useradd"], risk="low"),
            make_cmd("groupdel", "删除用户组", "操作系统/Linux扩展命令",
                     examples=[["sudo groupdel developers", "删除 developers 组"]],
                     related=["groupadd", "gpasswd"], risk="medium", risk_desc="删除仍有成员用户的组可能导致权限问题"),
            make_cmd("passwd", "修改用户密码", "操作系统/Linux扩展命令",
                     usage="passwd [OPTIONS] [LOGIN]",
                     options=["-l 锁定密码", "-u 解锁密码", "-d 删除密码"],
                     examples=[["passwd", "修改当前用户密码"], ["sudo passwd alice", "修改 alice 密码"]],
                     related=["useradd", "sudo"], risk="high", risk_desc="锁定或删除密码会导致无法登录，请谨慎使用 root 权限"),
            make_cmd("su", "切换用户身份", "操作系统/Linux扩展命令",
                     usage="su [OPTIONS] [LOGIN]",
                     options=["- 切换环境变量", "-c 执行命令后返回", "-s 指定 shell"],
                     examples=[["su - alice", "完全切换到 alice 环境"], ["su -c 'whoami' alice", "以 alice 执行单条命令"]],
                     related=["sudo", "sudo -i"], risk="medium", risk_desc="切换到 root 后操作具有全局影响，请注意命令范围"),
            make_cmd("visudo", "安全编辑 sudoers 文件", "操作系统/Linux扩展命令",
                     options=["-c 检查 sudoers 语法", "-f 指定 sudoers 文件"],
                     examples=[["sudo visudo", "编辑 /etc/sudoers"], ["sudo visudo -c", "检查 sudoers 语法"]],
                     related=["sudo", "usermod"], risk="critical", risk_desc="错误的 sudoers 配置可能导致无法提权或权限过大，编辑前请备份"),
            make_cmd("journalctl", "查询 systemd 日志", "操作系统/Linux扩展命令",
                     usage="journalctl [OPTIONS]",
                     options=["-u 指定服务单元", "-f 实时跟踪", "--since 指定开始时间", "--no-pager 不分页"],
                     examples=[["journalctl -u nginx", "查看 nginx 服务日志"], ["journalctl -f -u myapp", "实时跟踪 myapp 日志"]],
                     related=["systemctl", "dmesg"], risk="low"),
            make_cmd("hostnamectl", "查看和设置主机名", "操作系统/Linux扩展命令",
                     options=["status 查看状态", "set-hostname 设置静态主机名", "set-icon-name 设置图标名"],
                     examples=[["hostnamectl status", "查看主机名信息"], ["sudo hostnamectl set-hostname web01", "设置主机名为 web01"]],
                     related=["hostname", "timedatectl"], risk="low"),
            make_cmd("locale", "显示和设置区域设置", "操作系统/Linux扩展命令",
                     options=["-a 列出所有可用区域", "-m 列出所有字符映射"],
                     examples=[["locale", "显示当前区域设置"], ["locale -a | grep zh_CN", "列出中文区域设置"]],
                     related=["localectl", "env"], risk="low"),
            make_cmd("tar", "归档和压缩工具", "操作系统/Linux扩展命令",
                     usage="tar [OPTIONS] [ARCHIVE] [FILE...]",
                     options=["-c 创建归档", "-x 解压归档", "-z 使用 gzip", "-f 指定文件名", "-v 显示过程"],
                     examples=[["tar -czvf backup.tar.gz /etc", "压缩 /etc 目录"], ["tar -xzvf backup.tar.gz -C /tmp", "解压到 /tmp"]],
                     related=["gzip", "zip"], risk="medium", risk_desc="解压到错误目录或覆盖现有文件会造成混乱，请确认目标路径"),
            make_cmd("bzip2", "块排序文件压缩工具", "操作系统/Linux扩展命令",
                     usage="bzip2 [OPTIONS] [FILE...]",
                     options=["-d 解压缩", "-k 保留原文件", "-f 强制覆盖"],
                     examples=[["bzip2 file.txt", "压缩 file.txt"], ["bzip2 -dk file.txt.bz2", "解压缩并保留压缩包"]],
                     related=["gzip", "xz"], risk="low", risk_desc="默认删除原文件，建议使用 -k 保留备份"),
            make_cmd("xz", "高压缩比文件压缩工具", "操作系统/Linux扩展命令",
                     usage="xz [OPTIONS] [FILE...]",
                     options=["-d 解压缩", "-k 保留原文件", "-T 指定线程数"],
                     examples=[["xz file.txt", "压缩 file.txt"], ["xz -dk file.txt.xz", "解压缩并保留压缩包"]],
                     related=["gzip", "bzip2"], risk="low", risk_desc="xz 压缩耗时较长，默认删除原文件，请使用 -k 保留"),
            make_cmd("zip", "创建 ZIP 归档", "操作系统/Linux扩展命令",
                     usage="zip [OPTIONS] ARCHIVE FILES...",
                     options=["-r 递归压缩目录", "-e 加密", "-q 静默模式"],
                     examples=[["zip -r backup.zip docs/", "递归压缩 docs 目录"], ["zip -e secret.zip file.txt", "创建加密 ZIP"]],
                     related=["unzip", "tar"], risk="low"),
            make_cmd("unzip", "解压 ZIP 归档", "操作系统/Linux扩展命令",
                     usage="unzip [OPTIONS] ARCHIVE",
                     options=["-d 指定解压目录", "-o 覆盖现有文件", "-l 列出内容"],
                     examples=[["unzip archive.zip -d /tmp/extract", "解压到指定目录"], ["unzip -l archive.zip", "列出归档内容"]],
                     related=["zip", "tar"], risk="medium", risk_desc="-o 会直接覆盖目标文件，建议先查看内容"),
            make_cmd("uname", "显示系统内核信息", "操作系统/Linux扩展命令",
                     options=["-a 显示所有信息", "-r 显示内核版本", "-m 显示机器硬件名"],
                     examples=[["uname -a", "显示完整系统信息"], ["uname -r", "显示内核版本"]],
                     related=["hostname", "cat /etc/os-release"], risk="low"),
            make_cmd("date", "显示或设置系统日期时间", "操作系统/Linux扩展命令",
                     usage="date [OPTIONS] [+FORMAT]",
                     options=["-u 显示 UTC", "-d 显示指定时间", "-s 设置时间（需 root）"],
                     examples=[["date", "显示当前日期时间"], ["date +%Y-%m-%d", "以指定格式输出日期"]],
                     related=["timedatectl", "cal"], risk="medium", risk_desc="手动设置时间可能影响日志顺序和定时任务，建议使用 NTP"),
            make_cmd("env", "显示或修改环境变量后执行命令", "操作系统/Linux扩展命令",
                     usage="env [OPTIONS] [-] [NAME=VALUE]... [COMMAND [ARGS]]",
                     options=["-i 忽略继承的环境", "-u 删除变量"],
                     examples=[["env", "显示所有环境变量"], ["env VAR=value ./app", "临时设置变量后运行程序"]],
                     related=["export", "printenv"], risk="low"),
            make_cmd("ulimit", "显示或设置 shell 资源限制", "操作系统/Linux扩展命令",
                     options=["-a 显示所有限制", "-n 文件描述符数量", "-u 最大进程数"],
                     examples=[["ulimit -a", "显示当前资源限制"], ["ulimit -n 65536", "设置最大打开文件数为 65536"]],
                     related=["sysctl", "systemctl"], risk="medium", risk_desc="设置过低可能导致服务无法启动，过高可能耗尽系统资源"),
            make_cmd("nice", "以指定优先级运行命令", "操作系统/Linux扩展命令",
                     usage="nice [OPTIONS] [COMMAND [ARGS]]",
                     options=["-n 指定 nice 值（-20 到 19）"],
                     examples=[["nice -n 10 ./long-task", "以较低优先级运行任务"], ["nice -n -5 ./critical-task", "以较高优先级运行任务（需 root）"]],
                     related=["renice", "top"], risk="low"),
            make_cmd("renice", "修改运行中进程的优先级", "操作系统/Linux扩展命令",
                     usage="renice [OPTIONS] PRIORITY [[-p] PID...]",
                     options=["-p 按 PID", "-u 按用户", "-g 按进程组"],
                     examples=[["sudo renice -n -5 -p 1234", "提升进程 1234 的优先级"], ["sudo renice -n 10 -u alice", "降低 alice 所有进程优先级"]],
                     related=["nice", "top"], risk="medium", risk_desc="调整关键系统进程优先级可能影响稳定性，请谨慎"),
            make_cmd("timeout", "在指定时间后终止命令", "操作系统/Linux扩展命令",
                     usage="timeout [OPTIONS] DURATION COMMAND [ARGS]",
                     options=["-s 指定发送的信号", "-k 强制终止前的宽限时间", "--preserve-status 保留退出码"],
                     examples=[["timeout 30s ./job.sh", "30 秒后终止 job.sh"], ["timeout -s 9 10m ./long-task", "10 分钟后强制 kill"]],
                     related=["nohup", "cron"], risk="low"),
            make_cmd("at", "在指定时间执行一次性任务", "操作系统/Linux扩展命令",
                     usage="at [OPTIONS] TIME",
                     options=["-f 从文件读取命令", "-l 列出待执行作业", "-r 删除作业"],
                     examples=[["echo 'reboot' | at 02:00", "安排凌晨 2 点重启"], ["at -f backup.sh now + 1 hour", "1 小时后执行脚本"]],
                     related=["crontab", "batch"], risk="high", risk_desc="at 任务会在未来以当前环境执行，错误命令可能造成严重后果，请验证脚本"),
        ],
    },
    "network/tools-extra.yaml": {
        "category": "网络工具/扩展工具",
        "description": "网络抓包、代理、扫描、探测等扩展工具",
        "commands": [
            make_cmd("tshark", "Wireshark 命令行抓包工具", "网络工具/扩展工具",
                     install_required=True, install_method="包管理器安装，如 sudo apt install tshark",
                     options=["-i 指定网卡", "-w 写入 pcap 文件", "-f 设置捕获过滤器", "-r 读取 pcap"],
                     examples=[["sudo tshark -i eth0 -w capture.pcap", "在 eth0 抓包并保存"], ["tshark -r capture.pcap -Y http", "读取并过滤 HTTP 包"]],
                     related=["tcpdump", "wireshark"], risk="high", risk_desc="抓包会捕获敏感流量，请遵守数据隐私与合规要求"),
            make_cmd("termshark", "终端交互式 TUI 抓包工具", "网络工具/扩展工具",
                     install_required=True, install_method="pip install termshark 或参考 https://github.com/gcla/termshark",
                     options=["-i 指定网卡", "-r 读取 pcap", "-f 捕获过滤器"],
                     examples=[["sudo termshark -i eth0", "终端交互式抓包"], ["termshark -r capture.pcap", "交互式查看 pcap"]],
                     related=["tshark", "tcpdump"], risk="high", risk_desc="查看网络流量可能涉及敏感信息，请确保授权"),
            make_cmd("tcpflow", "TCP 流重组与捕获工具", "网络工具/扩展工具",
                     install_required=True, install_method="包管理器安装，如 sudo apt install tcpflow",
                     options=["-i 指定网卡", "-o 输出目录", "-c 输出到控制台"],
                     examples=[["sudo tcpflow -i eth0 port 80", "捕获 eth0 上 80 端口的 TCP 流"], ["tcpflow -r capture.pcap", "从 pcap 重组流"]],
                     related=["tcpdump", "tshark"], risk="high", risk_desc="重组流会还原明文数据，请遵守隐私政策"),
            make_cmd("ngrep", "网络数据包内容过滤工具", "网络工具/扩展工具",
                     install_required=True, install_method="包管理器安装，如 sudo apt install ngrep",
                     options=["-i 忽略大小写", "-W byline", "-q 静默", "-d 指定网卡"],
                     examples=[["sudo ngrep -d eth0 'GET' 'tcp port 80'", "过滤 80 端口的 GET 请求"], ["sudo ngrep -q 'password' 'port 3306'", "查找含 password 的流量"]],
                     related=["tcpdump", "grep"], risk="high", risk_desc="匹配敏感关键词会泄露数据，请仅在授权环境使用"),
            make_cmd("socat", "双向数据转发工具，号称 netcat 增强版", "网络工具/扩展工具",
                     install_required=True, install_method="包管理器安装，如 sudo apt install socat",
                     options=["-u 单向模式", "-d 增加调试级别", "TCP-LISTEN", "TCP"],
                     examples=[["socat TCP-LISTEN:8080,fork TCP:192.168.1.10:80", "将本地 8080 转发到远程 80"], ["socat - UNIX-CONNECT:/var/run/docker.sock", "通过 socat 连接 Docker socket"]],
                     related=["nc", "ssh -L"], risk="medium", risk_desc="端口转发会暴露内部服务，请确认访问控制和防火墙"),
            make_cmd("telnet", "基于文本的远程登录/端口探测工具", "网络工具/扩展工具",
                     install_required=True, install_method="多数系统预装或包管理器安装",
                     options=["-4 只使用 IPv4", "-6 只使用 IPv6", "port 指定端口"],
                     examples=[["telnet localhost 25", "测试本地 25 端口"], ["telnet example.com 80", "探测远程 80 端口"]],
                     related=["nc", "ssh"], risk="medium", risk_desc="telnet 明文传输，不建议用于生产认证，优先使用 ssh"),
            make_cmd("proxychains", "强制任意程序通过代理连接网络", "网络工具/扩展工具",
                     install_required=True, install_method="包管理器安装，如 sudo apt install proxychains4",
                     options=["-q 静默模式", "-f 指定配置文件"],
                     examples=[["proxychains curl https://example.com", "通过代理访问目标"], ["proxychains -q nmap -sT target", "通过代理进行 TCP 扫描"]],
                     related=["nc", "sshuttle"], risk="medium", risk_desc="代理配置错误会导致流量绕行或泄露，请确认代理安全"),
            make_cmd("amass", "深度子域名枚举与资产发现", "网络工具/扩展工具",
                     install_required=True, install_method="参考 https://github.com/owasp-amass/amass/releases",
                     options=["enum 枚举", "-d 目标域名", "-o 输出文件", "-active 主动模式"],
                     examples=[["amass enum -d example.com", "枚举 example.com 子域名"], ["amass enum -d example.com -o subs.txt", "保存结果"]],
                     related=["subfinder", "httpx"], risk="medium", risk_desc="主动枚举可能触发目标告警，请仅对授权域名执行"),
            make_cmd("dnsrecon", "DNS 枚举与区域传送检测", "网络工具/扩展工具",
                     install_required=True, install_method="参考 https://github.com/darkoperator/dnsrecon",
                     options=["-d 目标域名", "-t 枚举类型", "-D 字典文件"],
                     examples=[["dnsrecon -d example.com", "枚举 DNS 记录"], ["dnsrecon -d example.com -t axfr", "检测区域传送漏洞"]],
                     related=["dig", "amass"], risk="medium", risk_desc="大量 DNS 查询可能被目标视为扫描，请控制速率"),
            make_cmd("dog", "友好的命令行 DNS 客户端", "网络工具/扩展工具",
                     install_required=True, install_method="参考 https://github.com/ogham/dog/releases",
                     options=["-t 指定记录类型", "-n 指定名称服务器", "--json JSON 输出"],
                     examples=[["dog example.com", "查询 A 记录"], ["dog example.com MX -n 8.8.8.8", "使用指定 DNS 查询 MX"]],
                     related=["dig", "host"], risk="low"),
            make_cmd("hping3", "自定义 TCP/IP 数据包生成与探测工具", "网络工具/扩展工具",
                     install_required=True, install_method="包管理器安装，如 sudo apt install hping3",
                     options=["-S SYN 扫描", "-p 目标端口", "-c 发送次数", "--flood 泛洪模式"],
                     examples=[["sudo hping3 -S -p 80 -c 4 example.com", "发送 SYN 探测 80 端口"], ["sudo hping3 --flood -p 80 example.com", "泛洪测试（谨慎）"]],
                     related=["nmap", "nping"], risk="critical", risk_desc="泛洪模式会制造拒绝服务，严禁对未授权目标使用"),
            make_cmd("locust", "Python 编写的可编程负载测试工具", "网络工具/扩展工具",
                     install_required=True, install_method="pip install locust",
                     options=["-f 指定 locustfile", "--host 目标主机", "-u 用户数", "-r 每秒启动数"],
                     examples=[["locust -f locustfile.py --host https://example.com", "启动 Locust Web 界面"], ["locust -f locustfile.py -u 100 -r 10 --run-time 60s --headless", "无头模式运行 60 秒"]],
                     related=["k6", "wrk"], risk="high", risk_desc="Locust 压测会消耗目标资源，请获得授权并配置限流"),
            make_cmd("artillery", "现代 Node.js 负载测试与 SRE 工具", "网络工具/扩展工具",
                     install_required=True, install_method="npm install -g artillery",
                     options=["run 运行测试", "quick 快速压测", "-o 输出报告"],
                     examples=[["artillery quick --count 10 --num 50 https://example.com", "快速压测"], ["artillery run load-test.yml", "运行 YAML 压测脚本"]],
                     related=["k6", "locust"], risk="high", risk_desc="压测可能影响生产服务，请在授权沙箱或测试环境执行"),
            make_cmd("fortio", "Istio 配套的负载测试与 echo 服务器", "网络工具/扩展工具",
                     install_required=True, install_method="参考 https://github.com/fortio/fortio/releases",
                     options=["load 压测", "server 启动 echo 服务器", "-qps 每秒查询数", "-t 持续时间"],
                     examples=[["fortio load -qps 100 -t 30s https://example.com", "以 100 QPS 压测 30 秒"], ["fortio server", "启动 echo 服务器"]],
                     related=["k6", "wrk"], risk="high", risk_desc="高 QPS 压测会消耗目标资源，请获得授权"),
            make_cmd("iftop", "实时显示网络接口带宽使用", "网络工具/扩展工具",
                     install_required=True, install_method="包管理器安装，如 sudo apt install iftop",
                     options=["-i 指定网卡", "-n 禁用 DNS", "-B 以字节显示"],
                     examples=[["sudo iftop -i eth0", "查看 eth0 实时流量"], ["sudo iftop -nB -i eth0", "以字节显示且不做 DNS 解析"]],
                     related=["nethogs", "bmon"], risk="low"),
        ],
    },
    "database/extra.yaml": {
        "category": "数据库工具/扩展工具",
        "description": "NoSQL、NewSQL、图数据库等扩展命令",
        "commands": [
            make_cmd("mongorestore", "从 mongodump 备份恢复 MongoDB 数据", "数据库工具/扩展工具",
                     install_required=True, install_method="随 MongoDB Database Tools 安装",
                     options=["--uri 连接 URI", "--nsInclude 包含命名空间", "--drop 恢复前删除"],
                     examples=[["mongorestore --uri='mongodb://localhost:27017' /backup/mongo", "恢复备份"], ["mongorestore --db mydb /backup/mongo/mydb", "恢复指定数据库"]],
                     related=["mongodump", "mongosh"], risk="high", risk_desc="--drop 会清空现有集合，恢复前请确认备份正确"),
            make_cmd("mongoimport", "将 JSON/CSV/TSV 导入 MongoDB", "数据库工具/扩展工具",
                     install_required=True, install_method="随 MongoDB Database Tools 安装",
                     options=["--db 数据库", "--collection 集合", "--file 输入文件", "--headerline"],
                     examples=[["mongoimport --db mydb --collection users --file users.json", "导入 JSON"], ["mongoimport --db mydb --collection users --type=csv --headerline --file users.csv", "导入 CSV"]],
                     related=["mongoexport", "mongosh"], risk="medium", risk_desc="导入会写入目标集合，可能覆盖现有数据"),
            make_cmd("mongostat", "实时显示 MongoDB 实例统计信息", "数据库工具/扩展工具",
                     install_required=True, install_method="随 MongoDB Database Tools 安装",
                     options=["--host 主机", "--rowcount 行数", "--discover 发现副本集成员"],
                     examples=[["mongostat --host localhost:27017", "实时监控本地实例"], ["mongostat --discover", "监控整个副本集"]],
                     related=["mongotop", "mongosh"], risk="low"),
            make_cmd("mongotop", "实时显示 MongoDB 集合级读写时间", "数据库工具/扩展工具",
                     install_required=True, install_method="随 MongoDB Database Tools 安装",
                     options=["--host 主机", "--locks 显示锁信息", "--sleep 采样间隔"],
                     examples=[["mongotop 5", "每 5 秒采样一次"], ["mongotop --host rs0/mongo1:27017", "监控副本集"]],
                     related=["mongostat", "mongosh"], risk="low"),
            make_cmd("cockroach", "CockroachDB 分布式 SQL 数据库 CLI", "数据库工具/扩展工具",
                     install_required=True, install_method="参考 https://www.cockroachlabs.com/docs/stable/install-cockroachdb-linux",
                     options=["sql 启动 SQL shell", "init 初始化集群", "node 管理节点", "start 启动节点"],
                     examples=[["cockroach sql --insecure", "连接不安全模式集群"], ["cockroach init --insecure --host=node1", "初始化集群"]],
                     related=["psql", "tidb-ctl"], risk="high", risk_desc="init 和节点管理操作会影响整个集群，请在测试环境验证"),
            make_cmd("tidb-ctl", "TiDB 集群诊断与管理工具", "数据库工具/扩展工具",
                     install_required=True, install_method="参考 https://docs.pingcap.com/tidb/stable/tidb-control",
                     options=["schema 查看 schema", "region 查看 region", "etcd 查看 etcd"],
                     examples=[["tidb-ctl schema in mysql", "查看 mysql 数据库 schema"], ["tidb-ctl region -i 1", "查看 region 信息"]],
                     related=["mysql", "cockroach"], risk="medium", risk_desc="直接操作 TiDB 内部元数据可能导致不一致，请谨慎"),
            make_cmd("ysqlsh", "YugabyteDB 兼容 PostgreSQL 的 SQL Shell", "数据库工具/扩展工具",
                     install_required=True, install_method="随 YugabyteDB 安装",
                     options=["-h 主机", "-p 端口", "-d 数据库", "-c 执行命令"],
                     examples=[["ysqlsh -h localhost -d yugabyte", "连接本地 YugabyteDB"], ["ysqlsh -c 'SELECT version();'", "执行 SQL"]],
                     related=["psql", "ycqlsh"], risk="low"),
            make_cmd("ycqlsh", "YugabyteDB Cassandra 兼容 CQL Shell", "数据库工具/扩展工具",
                     install_required=True, install_method="随 YugabyteDB 安装",
                     options=["-e 执行 CQL", "-k keyspace", "--ssl"],
                     examples=[["ycqlsh localhost 9042", "连接 YCQL"], ["ycqlsh -e 'DESCRIBE KEYSPACES;'", "列出 keyspace"]],
                     related=["cqlsh", "ysqlsh"], risk="low"),
            make_cmd("neo4j-admin", "Neo4j 图数据库管理工具", "数据库工具/扩展工具",
                     install_required=True, install_method="随 Neo4j 安装",
                     options=["database 管理数据库", "dump 备份", "load 恢复", "check-consistency"],
                     examples=[["neo4j-admin database dump neo4j --to-path=/backup", "备份数据库"], ["neo4j-admin database load neo4j --from-path=/backup", "恢复数据库"]],
                     related=["cypher-shell", "neo4j"], risk="high", risk_desc="dump/load 会操作数据库文件，操作前请停止服务并备份"),
            make_cmd("cassandra-stress", "Cassandra 压力测试工具", "数据库工具/扩展工具",
                     install_required=True, install_method="随 Apache Cassandra 安装",
                     options=["user 自定义 profile", "write 写压测", "read 读压测", "-node 目标节点"],
                     examples=[["cassandra-stress write -node 127.0.0.1", "写入压力测试"], ["cassandra-stress read duration=5m -rate threads=50", "5 分钟读压测"]],
                     related=["cqlsh", "nodetool"], risk="high", risk_desc="压测会大量消耗 Cassandra 资源，请避开业务高峰并获授权"),
            make_cmd("mysqlslap", "MySQL 负载模拟与压测工具", "数据库工具/扩展工具",
                     install_required=True, install_method="随 MySQL 客户端安装",
                     options=["--auto-generate-sql", "--concurrency", "--iterations", "--engine"],
                     examples=[["mysqlslap --auto-generate-sql --concurrency=10 --iterations=100", "自动生成 SQL 压测"], ["mysqlslap --query='SELECT 1' --concurrency=50", "压测指定查询"]],
                     related=["mysql", "mysqladmin"], risk="high", risk_desc="压测会影响生产库性能，请在测试环境或低峰期执行"),
            make_cmd("pgbench", "PostgreSQL 基准测试工具", "数据库工具/扩展工具",
                     install_required=True, install_method="随 PostgreSQL 客户端安装",
                     options=["-i 初始化测试数据", "-c 并发客户端", "-t 每个客户端事务数", "-T 测试时长"],
                     examples=[["pgbench -i mydb", "初始化测试数据"], ["pgbench -c 10 -T 60 mydb", "10 并发压测 60 秒"]],
                     related=["psql", "pg_dump"], risk="high", risk_desc="压测会消耗 PG 资源，请在测试实例上执行"),
        ],
    },
    "bigdata/extra.yaml": {
        "category": "大数据/扩展工具",
        "description": "大数据生态的扩展命令和子系统",
        "commands": [
            make_cmd("mapred", "Hadoop MapReduce 管理命令", "大数据/扩展工具",
                     install_required=True, install_method="随 Hadoop 安装",
                     options=["job 查看/管理作业", "queues 查看队列", "classpath"],
                     examples=[["mapred job -list", "列出所有 MapReduce 作业"], ["mapred job -kill job_12345_0001", "终止指定作业"]],
                     related=["hadoop", "yarn"], risk="medium", risk_desc="终止作业会影响计算结果，请确认后再执行"),
            make_cmd("hbase shell", "HBase 交互式 Shell", "大数据/扩展工具",
                     install_required=True, install_method="随 Apache HBase 安装",
                     options=["-n 非交互模式", "-d 调试模式"],
                     examples=[["hbase shell", "启动 HBase Shell"], ["echo 'list' | hbase shell -n", "非交互列出表"]],
                     related=["hive", "hdfs"], risk="high", risk_desc="drop、disable 表会丢失数据，执行前请确认"),
            make_cmd("zookeeper-shell", "ZooKeeper 命令行客户端", "大数据/扩展工具",
                     install_required=True, install_method="随 Apache ZooKeeper 安装",
                     options=["-server 指定服务器"],
                     examples=[["zookeeper-shell localhost:2181", "连接本地 ZooKeeper"], ["echo 'ls /' | zookeeper-shell localhost:2181", "列出根节点"]],
                     related=["kafka-topics.sh", "hdfs"], risk="medium", risk_desc="删除 ZooKeeper 节点可能影响 Kafka/HBase 等依赖服务"),
            make_cmd("kafka-connect", "Kafka Connect 连接器管理 CLI", "大数据/扩展工具",
                     install_required=True, install_method="随 Apache Kafka 安装",
                     options=["standalone 单机模式", "distributed 分布式模式"],
                     examples=[["connect-standalone.sh connect-standalone.properties source.properties", "启动单机连接器"], ["connect-distributed.sh connect-distributed.properties", "启动分布式 Connect"]],
                     related=["kafka-topics.sh", "debezium"], risk="medium", risk_desc="连接器配置错误会导致数据重复或丢失，请验证 topic 与 schema"),
            make_cmd("kafka-configs.sh", "Kafka 配置管理工具", "大数据/扩展工具",
                     install_required=True, install_method="随 Apache Kafka 安装",
                     options=["--entity-type 实体类型", "--entity-name 实体名称", "--alter 修改配置"],
                     examples=[["kafka-configs.sh --bootstrap-server localhost:9092 --entity-type topics --entity-name mytopic --describe", "查看 topic 配置"], ["kafka-configs.sh --alter --add-config retention.ms=86400000 --entity-type topics --entity-name mytopic", "修改 retention"]],
                     related=["kafka-topics.sh", "kafka-consumer-groups.sh"], risk="high", risk_desc="修改 topic/broker 配置会影响性能和数据保留策略，请评估影响"),
            make_cmd("kafka-producer-perf-test", "Kafka 生产者性能测试", "大数据/扩展工具",
                     install_required=True, install_method="随 Apache Kafka 安装",
                     options=["--topic 目标 topic", "--num-records 记录数", "--record-size 记录大小", "--throughput 吞吐量"],
                     examples=[["kafka-producer-perf-test.sh --topic test --num-records 100000 --record-size 1024 --throughput 1000", "测试生产者性能"], ["kafka-producer-perf-test.sh --topic test --num-records 10000 --record-size 512", "小批量测试"]],
                     related=["kafka-consumer-perf-test", "kafka-topics.sh"], risk="high", risk_desc="压测会写入大量数据到 Kafka，请确认 topic 配置和磁盘空间"),
            make_cmd("kafka-consumer-perf-test", "Kafka 消费者性能测试", "大数据/扩展工具",
                     install_required=True, install_method="随 Apache Kafka 安装",
                     options=["--topic 目标 topic", "--messages 消费消息数", "--threads 线程数"],
                     examples=[["kafka-consumer-perf-test.sh --topic test --messages 100000 --threads 4", "测试消费者性能"], ["kafka-consumer-perf-test.sh --topic test --messages 10000", "小批量测试"]],
                     related=["kafka-producer-perf-test", "kafka-consumer-groups.sh"], risk="medium", risk_desc="消费压测可能影响同一 consumer group 的正式消费者"),
            make_cmd("livy-submit", "通过 Livy 提交 Spark 作业到集群", "大数据/扩展工具",
                     install_required=True, install_method="参考 https://livy.apache.org/get-started/",
                     options=["--file 提交文件", "--class 主类", "--args 程序参数"],
                     examples=[["livy-submit --file job.py --class main", "提交 Python 作业"], ["curl -X POST -H 'Content-Type: application/json' -d '{\"file\":\"job.py\"}' http://livy:8998/batches", "通过 REST 提交"]],
                     related=["spark-submit", "pyspark"], risk="medium", risk_desc="REST 提交时请保护 Livy 服务端点，避免未授权访问"),
            make_cmd("nifi", "Apache NiFi 数据流 CLI", "大数据/扩展工具",
                     install_required=True, install_method="参考 https://nifi.apache.org/docs/nifi-docs/html/getting-started.html",
                     options=["--version", "flow 导入/导出", "pg-get-root"],
                     examples=[["nifi flow import --inputFile flow.json", "导入数据流"], ["nifi pg-get-root", "获取根进程组 ID"]],
                     related=["airflow", "kafka-connect"], risk="medium", risk_desc="导入/修改流程会改变数据流转，请在测试环境验证"),
            make_cmd("logstash", "日志收集与转换管道", "大数据/扩展工具",
                     install_required=True, install_method="参考 https://www.elastic.co/guide/en/logstash/current/installing-logstash.html",
                     options=["-f 指定配置文件", "-e 直接指定管道", "-t 测试配置", "--config.reload.automatic"],
                     examples=[["logstash -f logstash.conf", "启动 Logstash"], ["logstash -e 'input { stdin {} } output { stdout {} }'", "从 stdin 读取并输出"]],
                     related=["filebeat", "elasticsearch"], risk="medium", risk_desc="错误的 grok/filter 会导致日志解析失败或数据丢失，请先用 -t 测试"),
        ],
    },
    "container/cloudnative-extra.yaml": {
        "category": "容器编排/云原生扩展",
        "description": "Service Mesh、Secret、本地集群、镜像构建等云原生扩展工具",
        "commands": [
            make_cmd("vault", "HashiCorp Vault 密钥管理 CLI", "容器编排/云原生扩展",
                     install_required=True, install_method="参考 https://developer.hashicorp.com/vault/downloads",
                     options=["kv 管理键值对", "auth 管理认证", "policy 管理策略", "status"],
                     examples=[["vault status", "查看 Vault 状态"], ["vault kv get secret/myapp", "读取密钥"]],
                     related=["consul", "kubectl"], risk="critical", risk_desc="Vault 管理敏感凭据，错误策略或 root token 泄露会造成严重安全事故"),
            make_cmd("consul", "HashiCorp Consul 服务网格与发现", "容器编排/云原生扩展",
                     install_required=True, install_method="参考 https://developer.hashicorp.com/consul/downloads",
                     options=["agent 启动代理", "kv 管理键值", "catalog 查看服务", "connect"],
                     examples=[["consul agent -dev", "开发模式启动 Consul"], ["consul kv get -recurse config/", "递归读取配置"]],
                     related=["vault", "envoy"], risk="medium", risk_desc="Consul 为控制平面，配置错误会影响服务发现"),
            make_cmd("nomad", "HashiCorp Nomad 工作负载调度器", "容器编排/云原生扩展",
                     install_required=True, install_method="参考 https://developer.hashicorp.com/nomad/downloads",
                     options=["job run 运行作业", "status 查看状态", "alloc 管理分配"],
                     examples=[["nomad job run example.nomad", "提交 Nomad 作业"], ["nomad status", "查看所有作业状态"]],
                     related=["consul", "vault"], risk="medium", risk_desc="job stop 会停止工作负载，请确认影响范围"),
            make_cmd("envoy", "云原生高性能代理", "容器编排/云原生扩展",
                     install_required=True, install_method="参考 https://www.envoyproxy.io/docs/envoy/latest/start/install",
                     options=["-c 指定配置文件", "--mode", "--admin-address-path"],
                     examples=[["envoy -c envoy.yaml", "启动 Envoy"], ["envoy --mode validate -c envoy.yaml", "验证配置"]],
                     related=["istioctl", "consul"], risk="medium", risk_desc="Envoy 作为数据平面，配置错误会中断流量"),
            make_cmd("linkerd", "轻量级 Service Mesh CLI", "容器编排/云原生扩展",
                     install_required=True, install_method="参考 https://linkerd.io/2/getting-started/",
                     options=["check 检查集群", "install 安装控制平面", "inject 自动注入 sidecar", "stat 查看统计"],
                     examples=[["linkerd check", "检查 Linkerd 安装"], ["linkerd inject deploy.yml | kubectl apply -f -", "注入 sidecar 并部署"]],
                     related=["istioctl", "kubectl"], risk="medium", risk_desc="控制平面变更会影响流量治理，请在维护窗口执行"),
            make_cmd("jaeger-cli", "Jaeger 分布式追踪 CLI", "容器编排/云原生扩展",
                     install_required=True, install_method="参考 https://www.jaegertracing.io/download/",
                     options=["--query.query-port", "span 查询", "trace 查询"],
                     examples=[["jaeger-cli query --service myservice", "查询服务追踪"], ["jaeger-cli trace 123e4567", "查看指定 trace"]],
                     related=["otelcol", "tempo-cli"], risk="low"),
            make_cmd("tempo-cli", "Grafana Tempo 追踪查询 CLI", "容器编排/云原生扩展",
                     install_required=True, install_method="参考 https://grafana.com/docs/tempo/latest/setup/",
                     options=["--server 地址", "query 查询 trace"],
                     examples=[["tempo-cli query 123e4567", "查询 trace ID"], ["tempo-cli --server http://tempo:3200 search 'name=GET /api'", "搜索 span"]],
                     related=["jaeger-cli", "otelcol"], risk="low"),
            make_cmd("loki-cli", "Grafana Loki 日志查询 CLI（logcli）", "容器编排/云原生扩展",
                     install_required=True, install_method="参考 https://grafana.com/docs/loki/latest/getting-started/logcli/",
                     options=["--addr Loki 地址", "query 查询日志", "labels 列出标签"],
                     examples=[["logcli query '{job=\"varlogs\"}'", "查询 job 日志"], ["logcli labels", "列出所有标签"]],
                     related=["promtail", "grafana-server"], risk="low"),
            make_cmd("promtail", "Loki 日志收集 Agent", "容器编排/云原生扩展",
                     install_required=True, install_method="参考 https://grafana.com/docs/loki/latest/send-data/promtail/installation/",
                     options=["-config.file 配置文件", "-dry-run  dry-run 模式", "-inspect"],
                     examples=[["promtail -config.file=promtail.yml", "启动 Promtail"], ["promtail -config.file=promtail.yml -dry-run", "dry-run 验证"]],
                     related=["loki-cli", "fluent-bit"], risk="medium", risk_desc="错误的标签配置会导致日志无法查询或 cardinality 爆炸"),
            make_cmd("cert-manager", "Kubernetes 证书自动化管理（cmctl）", "容器编排/云原生扩展",
                     install_required=True, install_method="参考 https://cert-manager.io/docs/reference/cmctl/",
                     options=["check 检查", "status 查看证书状态", "renew 手动续期"],
                     examples=[["cmctl check api", "检查 cert-manager API"], ["cmctl status certificate mycert -n default", "查看证书状态"]],
                     related=["kubectl", "openssl"], risk="medium", risk_desc="手动 renew 或删除证书可能导致服务 TLS 中断"),
            make_cmd("external-dns", "Kubernetes DNS 记录自动同步", "容器编排/云原生扩展",
                     install_required=True, install_method="参考 https://kubernetes-sigs.github.io/external-dns/latest/",
                     options=["--provider 指定 DNS 服务商", "--source 指定来源", "--dry-run"],
                     examples=[["external-dns --provider aws --source ingress --dry-run", "dry-run 查看待同步记录"], ["external-dns --provider aws --source service", "同步 Service 到 DNS"]],
                     related=["kubectl", "aws"], risk="high", risk_desc="external-dns 会修改公共 DNS 记录，dry-run 验证后再执行"),
            make_cmd("clusterctl", "Cluster API 集群生命周期管理", "容器编排/云原生扩展",
                     install_required=True, install_method="参考 https://cluster-api.sigs.k8s.io/clusterctl/overview.html",
                     options=["init 初始化管理集群", "generate cluster 生成集群 YAML", "move 迁移集群"],
                     examples=[["clusterctl init --infrastructure aws", "初始化 AWS provider"], ["clusterctl generate cluster my-cluster --kubernetes-version v1.28.0 > cluster.yaml", "生成工作负载集群清单"]],
                     related=["kubectl", "kubeadm"], risk="high", risk_desc="clusterctl 管理 Kubernetes 集群生命周期，误操作可能影响管理平面"),
            make_cmd("crossplane", "Kubernetes 多云控制平面 CLI", "容器编排/云原生扩展",
                     install_required=True, install_method="参考 https://docs.crossplane.io/latest/software/install/",
                     options=["xpkg 管理包", "trace 追踪资源", "beta"],
                     examples=[["crossplane xpkg install provider crossplane/provider-aws", "安装 AWS provider"], ["crossplane trace resource mydb -n default", "追踪资源状态"]],
                     related=["kubectl", "terraform"], risk="medium", risk_desc="Managed Resources 会创建真实云资源，请确认 provider 配置"),
            make_cmd("k3s", "轻量级 Kubernetes 发行版", "容器编排/云原生扩展",
                     install_required=True, install_method="参考 https://docs.k3s.io/quick-start",
                     options=["server 启动 server", "agent 启动 agent", "kubectl 子命令"],
                     examples=[["curl -sfL https://get.k3s.io | sh -", "安装并启动 k3s"], ["k3s kubectl get nodes", "使用 k3s 内置 kubectl"]],
                     related=["kubectl", "kind"], risk="medium", risk_desc="k3s 会修改系统配置并启动容器，请确认环境隔离"),
            make_cmd("k0s", "零依赖单二进制 Kubernetes 发行版", "容器编排/云原生扩展",
                     install_required=True, install_method="参考 https://docs.k0sproject.io/stable/install/",
                     options=["controller 启动控制节点", "worker 启动工作节点", "status"],
                     examples=[["k0s install controller --single", "单节点安装"], ["k0s status", "查看集群状态"]],
                     related=["k3s", "kubectl"], risk="medium", risk_desc="k0s 需要 root 权限并配置系统服务，请在测试环境验证"),
            make_cmd("microk8s", "Ubuntu 官方轻量 Kubernetes 发行版", "容器编排/云原生扩展",
                     install_required=True, install_method="sudo snap install microk8s --classic",
                     options=["status 查看状态", "enable 启用插件", "kubectl 子命令"],
                     examples=[["microk8s status", "查看 MicroK8s 状态"], ["microk8s enable dns ingress", "启用 dns 和 ingress 插件"]],
                     related=["kubectl", "k3s"], risk="medium", risk_desc="snap 安装会修改系统，生产环境请先评估"),
            make_cmd("oc", "OpenShift 命令行工具", "容器编排/云原生扩展",
                     install_required=True, install_method="参考 https://docs.openshift.com/container-platform/latest/cli_reference/openshift_cli/getting-started-cli.html",
                     options=["login 登录", "new-project 创建项目", "adm 管理命令"],
                     examples=[["oc login https://api.example.com:6443", "登录 OpenShift"], ["oc new-project myproject", "创建新项目"]],
                     related=["kubectl", "helm"], risk="medium", risk_desc="oc 拥有 cluster-admin 能力时请谨慎使用"),
            make_cmd("docker buildx", "Docker 高级镜像构建插件", "容器编排/云原生扩展",
                     install_required=True, install_method="Docker Desktop 自带或 docker-buildx 插件",
                     usage="docker buildx [OPTIONS] COMMAND",
                     options=["build 构建", "create 创建 builder", "ls 列出 builder", "bake 批量构建"],
                     examples=[["docker buildx build --platform linux/amd64,linux/arm64 -t myapp .", "多平台构建"], ["docker buildx ls", "列出 builders"]],
                     related=["docker build", "buildkit"], risk="medium", risk_desc="多平台构建和缓存导出可能产生大量临时文件"),
            make_cmd("docker context", "Docker 上下文管理", "容器编排/云原生扩展",
                     usage="docker context [OPTIONS] COMMAND",
                     options=["create 创建上下文", "use 切换上下文", "ls 列出", "rm 删除"],
                     examples=[["docker context ls", "列出上下文"], ["docker context create remote --docker host=ssh://user@host", "创建远程上下文"]],
                     related=["docker", "kubectl config"], risk="low"),
            make_cmd("docker network", "Docker 网络管理", "容器编排/云原生扩展",
                     usage="docker network [OPTIONS] COMMAND",
                     options=["create 创建网络", "ls 列出", "inspect 查看", "rm 删除"],
                     examples=[["docker network create mynet", "创建桥接网络"], ["docker network connect mynet mycontainer", "连接容器到网络"]],
                     related=["docker run", "docker volume"], risk="low"),
            make_cmd("docker volume", "Docker 卷管理", "容器编排/云原生扩展",
                     usage="docker volume [OPTIONS] COMMAND",
                     options=["create 创建卷", "ls 列出", "inspect 查看", "rm 删除"],
                     examples=[["docker volume create myvol", "创建命名卷"], ["docker volume rm myvol", "删除卷"]],
                     related=["docker run", "docker network"], risk="high", risk_desc="删除卷会丢失持久化数据，请确认无容器使用"),
            make_cmd("docker system", "Docker 系统级维护命令", "容器编排/云原生扩展",
                     usage="docker system [OPTIONS] COMMAND",
                     options=["df 查看磁盘使用", "prune 清理未使用数据", "info 系统信息"],
                     examples=[["docker system df", "查看 Docker 磁盘使用"], ["docker system prune -a", "清理所有未使用镜像和卷（谨慎）"]],
                     related=["docker", "docker volume"], risk="high", risk_desc="prune 会删除未使用的镜像、容器、网络和卷，请确认后再执行"),
            make_cmd("buildkit", "Docker/Moby 下一代镜像构建工具包", "容器编排/云原生扩展",
                     install_required=True, install_method="参考 https://github.com/moby/buildkit/blob/master/README.md",
                     options=["buildctl 命令行", "--addr 指定 buildkitd 地址"],
                     examples=[["buildctl build --frontend dockerfile.v0 --local context=. --local dockerfile=.", "使用 Dockerfile 构建"], ["buildctl du", "查看磁盘使用"]],
                     related=["docker buildx", "kaniko"], risk="medium", risk_desc="构建会执行 Dockerfile 中的指令，请审查基础镜像和命令"),
            make_cmd("kaniko", "无需特权 Docker daemon 的镜像构建工具", "容器编排/云原生扩展",
                     install_required=True, install_method="参考 https://github.com/GoogleContainerTools/kaniko",
                     options=["--dockerfile Dockerfile", "--context", "--destination", "--no-push"],
                     examples=[["executor --dockerfile Dockerfile --context . --destination registry/myapp:v1", "构建并推送镜像"], ["executor --dockerfile Dockerfile --context . --no-push", "只构建不推送"]],
                     related=["docker build", "buildkit"], risk="medium", risk_desc="kaniko 会访问 registry 凭据，请确保 Secret 安全"),
            make_cmd("img", "由 buildkit 支持的无 daemon 镜像构建工具", "容器编排/云原生扩展",
                     install_required=True, install_method="参考 https://github.com/genuinetools/img",
                     options=["build 构建", "tag 标签", "push 推送", "pull 拉取"],
                     examples=[["img build -t myapp .", "构建镜像"], ["img tag myapp registry/myapp:v1", "打标签"]],
                     related=["buildkit", "docker"], risk="medium", risk_desc="img 以非 root 运行但仍在用户命名空间，注意缓存目录权限"),
            make_cmd("infracost", "云基础设施成本估算工具", "容器编排/云原生扩展",
                     install_required=True, install_method="参考 https://www.infracost.io/docs/#quick-start",
                     options=["breakdown 生成成本明细", "diff 比较成本差异", "--path 指定 IaC 目录"],
                     examples=[["infracost breakdown --path .", "估算当前目录 IaC 成本"], ["infracost diff --path . --compare-to infracost-base.json", "比较成本差异"]],
                     related=["terraform", "pulumi"], risk="low"),
            make_cmd("tfsec", "Terraform 静态安全扫描工具", "容器编排/云原生扩展",
                     install_required=True, install_method="参考 https://aquasecurity.github.io/tfsec/latest/guides/installation/",
                     options=["--tfvars-file 指定变量文件", "--exclude 排除检查", "--format 输出格式"],
                     examples=[["tfsec .", "扫描当前目录 Terraform"], ["tfsec --format json . > report.json", "输出 JSON 报告"]],
                     related=["checkov", "terraform"], risk="low"),
            make_cmd("atlantis", "Terraform 自动化 PR 工作流工具", "容器编排/云原生扩展",
                     install_required=True, install_method="参考 https://www.runatlantis.io/docs/installation-guide.html",
                     options=["plan 触发计划", "apply 触发应用", "version"],
                     examples=[["atlantis plan", "对当前 PR 执行 plan"], ["atlantis apply", "应用已批准的 plan"]],
                     related=["terraform", "github-actions"], risk="high", risk_desc="atlantis apply 会修改真实基础设施，请确保 PR 已审查"),
            make_cmd("snyk", "开发者安全扫描平台 CLI", "容器编排/云原生扩展",
                     install_required=True, install_method="参考 https://docs.snyk.io/snyk-cli/install-the-snyk-cli",
                     options=["test 扫描", "container test 扫描镜像", "code test 扫描代码", "monitor 监控"],
                     examples=[["snyk test", "扫描项目依赖漏洞"], ["snyk container test myapp:latest", "扫描容器镜像"]],
                     related=["trivy", "grype"], risk="low"),
        ],
    },
    "ai/llm-extra.yaml": {
        "category": "AI基础设施/扩展工具",
        "description": "大模型应用与平台扩展工具",
        "commands": [
            make_cmd("open-webui", "本地大模型 Web 聊天界面", "AI基础设施/扩展工具",
                     install_required=True, install_method="pip install open-webui 或 Docker 运行",
                     options=["serve 启动服务", "--port", "--host"],
                     examples=[["open-webui serve", "启动 Open WebUI 服务"], ["docker run -d -p 3000:8080 --gpus all -v ollama:/root/.ollama -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:ollama", "Docker 启动并挂载 Ollama"]],
                     related=["ollama", "llama.cpp"], risk="medium", risk_desc="WebUI 会暴露模型接口，请配置认证和网络访问控制"),
            make_cmd("anything-llm", "本地/私有化知识库与 LLM 对话平台", "AI基础设施/扩展工具",
                     install_required=True, install_method="参考 https://github.com/Mintplex-Labs/anything-llm/blob/master/BARE_METAL.md",
                     options=["start 启动服务", "setup 初始化"],
                     examples=[["yarn anything-llm start", "启动 AnythingLLM"], ["docker pull mintplexlabs/anythingllm && docker run -d -p 3001:3001 mintplexlabs/anythingllm", "Docker 启动"]],
                     related=["ollama", "docling"], risk="medium", risk_desc="上传文档可能包含敏感信息，请做好访问控制和数据隔离"),
            make_cmd("mcp", "Model Context Protocol CLI/服务器", "AI基础设施/扩展工具",
                     install_required=True, install_method="参考 https://modelcontextprotocol.io/quickstart",
                     options=["init 初始化", "run 运行服务器", "inspect 检查"],
                     examples=[["npx @anthropics/mcp-server-puppeteer", "运行官方示例 MCP 服务器"], ["uvx mcp-server-sqlite --db path/to/db.sqlite", "运行 SQLite MCP 服务器"]],
                     related=["openai-agents", "langchain"], risk="medium", risk_desc="MCP 服务器可能拥有文件/网络访问权限，请审查权限并隔离运行"),
            make_cmd("perplexity", "Perplexity API CLI", "AI基础设施/扩展工具",
                     install_required=True, install_method="pip install perplexity-python 或参考官方 SDK",
                     options=["--model", "--messages", "--stream"],
                     examples=[["perplexity ask 'What is RAG?'", "通过 CLI 提问"], ["perplexity --model sonar-pro --stream 'Explain Kubernetes'", "流式输出回答"]],
                     related=["groq", "openai-function-calling"], risk="low"),
            make_cmd("sweep", "AI 驱动的代码 issue 自动修复助手", "AI基础设施/扩展工具",
                     install_required=True, install_method="pip install sweepai 或 GitHub App",
                     options=["--issue 指定 issue", "--repo 指定仓库", "--branch"],
                     examples=[["sweep --issue 123 --repo myorg/myrepo", "根据 issue 生成修复 PR"], ["sweep --issue 'Fix memory leak in worker' --repo myorg/myrepo", "按描述生成修复"]],
                     related=["swe-agent", "aider"], risk="high", risk_desc="AI 自动修改代码可能引入 Bug，请严格审查生成的 PR 并通过 CI"),
        ],
    },
}


def main() -> int:
    meta = yaml.load(open(META_PATH, "r", encoding="utf-8"))
    existing_names = set()
    for rel_file in meta["data_files"]:
        path = DATA_DIR / rel_file
        if not path.exists():
            continue
        doc = yaml.load(open(path, "r", encoding="utf-8"))
        for cmd in doc.get("commands", []):
            existing_names.add(cmd["name"])

    total_added = 0
    for rel_file, spec in BATCH.items():
        path = DATA_DIR / rel_file
        path.parent.mkdir(parents=True, exist_ok=True)
        commands = []
        skipped = []
        for cmd in spec["commands"]:
            if cmd["name"] in existing_names:
                skipped.append(cmd["name"])
                continue
            commands.append(cmd)
            existing_names.add(cmd["name"])
        if not commands:
            print(f"{rel_file}: all commands already exist, skipped")
            continue
        doc = {
            "category": spec["category"],
            "description": spec["description"],
            "commands": commands,
        }
        with open(path, "w", encoding="utf-8") as f:
            yaml.dump(doc, f)
        # metadata
        cat_id = rel_file.replace("/", "_").replace("-", "_").replace(".", "_")
        meta["categories"][cat_id] = {
            "id": cat_id,
            "name": spec["category"],
            "description": spec["description"],
            "parent": "",
            "order": 200,
        }
        if rel_file not in meta["data_files"]:
            meta["data_files"].append(rel_file)
        print(f"{rel_file}: added {len(commands)}, skipped {len(skipped)}")
        total_added += len(commands)

    # update metadata description
    cmd_count = 0
    for rel_file in meta["data_files"]:
        doc = yaml.load(open(DATA_DIR / rel_file, "r", encoding="utf-8"))
        cmd_count += len(doc["commands"])
    meta["description"] = f"cmd4coder 命令行工具大全数据文件 - 覆盖 {len(meta['categories'])} 个分类, {cmd_count} 命令"

    with open(META_PATH, "w", encoding="utf-8") as f:
        yaml.dump(meta, f)
    print(f"\nTotal added: {total_added}, total commands: {cmd_count}, categories: {len(meta['categories'])}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
