#!/usr/bin/env python3
"""
最后一批补齐：硬件、编程语言工具链、CI/CD、云平台、系统诊断。
"""
import sys
from pathlib import Path
from ruamel.yaml import YAML

yaml = YAML()
yaml.preserve_quotes = True
yaml.default_flow_style = False

DATA_DIR = Path("data")
META_PATH = DATA_DIR / "metadata.yaml"


def opt(flag_desc: str) -> dict:
    parts = flag_desc.split(" ", 1)
    return {"flag": parts[0], "description": parts[1] if len(parts) > 1 else ""}


def ex(cmd: str, desc: str) -> dict:
    return {"command": cmd, "description": desc}


def make_cmd(
    name: str,
    desc: str,
    category: str,
    usage: str = None,
    options: list = None,
    examples: list = None,
    related: list = None,
    install_required: bool = False,
    install_method: str = None,
    platforms: list = None,
    risk: str = "low",
    risk_desc: str = None,
) -> dict:
    if usage is None:
        usage = f"{name} [OPTIONS] [ARGS]"
    if options is None:
        options = ["--help 显示帮助信息", "--version 显示版本信息"]
    if examples is None:
        examples = [[f"{name} --help", "查看帮助"], [f"{name} --version", "查看版本"]]
    if platforms is None:
        platforms = ["linux", "darwin"]
    if related is None:
        related = []
    cmd = {
        "name": name,
        "category": category,
        "install_required": install_required,
        "description": desc,
        "usage": [usage],
        "options": [opt(o) for o in options],
        "examples": [ex(e[0], e[1]) for e in examples],
        "platforms": platforms,
        "related_commands": related,
    }
    if install_required and install_method:
        cmd["install_method"] = install_method
    if risk in ("medium", "high", "critical"):
        if risk_desc is None:
            risk_desc = "操作前请确认参数、目标环境和影响范围，建议在测试环境先行验证。"
        cmd["risks"] = [{"level": risk, "description": risk_desc}]
    return cmd


BATCH = {
    "hardware/info.yaml": {
        "category": "硬件/系统信息",
        "description": "查看系统硬件配置、拓扑与 NUMA 信息",
        "commands": [
            make_cmd("lshw", "列出详细硬件配置", "硬件/系统信息",
                     install_required=True, install_method="包管理器安装，如 sudo apt install lshw",
                     options=["-short 简要输出", "-class 指定类别", "-json JSON 输出", "-sanitize 隐藏敏感信息"],
                     examples=[["sudo lshw -short", "简要列出硬件"], ["sudo lshw -class memory", "只查看内存"]],
                     related=["dmidecode", "inxi"], risk="low"),
            make_cmd("inxi", "友好的系统/硬件信息汇总工具", "硬件/系统信息",
                     install_required=True, install_method="包管理器安装，如 sudo apt install inxi",
                     options=["-F 完整输出", "-G 显卡", "-N 网络", "-D 硬盘", "-z 隐藏敏感"],
                     examples=[["inxi -F", "完整系统信息"], ["inxi -G", "显卡信息"]],
                     related=["lshw", "hardinfo"], risk="low"),
            make_cmd("hardinfo", "图形/命令行系统信息与基准测试", "硬件/系统信息",
                     install_required=True, install_method="包管理器安装，如 sudo apt install hardinfo",
                     options=["-r 生成报告", "-f 输出格式"],
                     examples=[["hardinfo -r -f html > report.html", "生成 HTML 报告"], ["hardinfo -r -f text", "文本报告"]],
                     related=["lshw", "inxi"], risk="low"),
            make_cmd("hwloc", "硬件拓扑抽象层工具", "硬件/系统信息",
                     install_required=True, install_method="包管理器安装，如 sudo apt install hwloc",
                     options=["--objects", "--no-io", "--of xml|txt"],
                     examples=[["hwloc-ls", "显示硬件拓扑"], ["hwloc-info", "显示摘要信息"]],
                     related=["lstopo", "numactl"], risk="low"),
            make_cmd("lstopo", "图形/文本化硬件拓扑查看器", "硬件/系统信息",
                     install_required=True, install_method="随 hwloc 安装",
                     options=["-v 详细", "--no-io", "--of png", "--output-format"],
                     examples=[["lstopo", "文本显示拓扑"], ["lstopo topology.png", "导出拓扑图"]],
                     related=["hwloc", "numactl"], risk="low"),
            make_cmd("numactl", "控制进程的 NUMA 内存与 CPU 策略", "硬件/系统信息",
                     usage="numactl [OPTIONS] COMMAND",
                     install_required=True, install_method="多数 Linux 预装或包管理器安装",
                     options=["--cpunodebind 绑定 CPU 节点", "--membind 绑定内存节点", "--interleave 交错", "--show 显示当前策略"],
                     examples=[["numactl --show", "显示当前 NUMA 策略"], ["numactl --cpunodebind=0 --membind=0 ./app", "绑定到节点 0"]],
                     related=["taskset", "lstopo"], risk="medium", risk_desc="错误绑定会降低性能或导致 OOM，请了解 NUMA 拓扑"),
            make_cmd("numastat", "显示每个 NUMA 节点的内存统计", "硬件/系统信息",
                     options=["-m 显示 MB", "-n 节点级", "-c 紧凑"],
                     examples=[["numastat", "查看 NUMA 内存统计"], ["numastat -m -n", "以 MB 显示节点级统计"]],
                     related=["numactl", "free"], risk="low"),
        ],
    },
    "hardware/sensors.yaml": {
        "category": "硬件/传感器与电源",
        "description": "温度、风扇、功耗与电源管理工具",
        "commands": [
            make_cmd("sensors", "读取硬件传感器数据（lm-sensors）", "硬件/传感器与电源",
                     install_required=True, install_method="包管理器安装 lm-sensors",
                     options=["-u 原始值", "-f 华氏度", "-A 平均", "-s 计算"],
                     examples=[["sensors", "显示 CPU/主板温度"], ["sensors -u coretemp-isa-0000", "显示原始传感器值"]],
                     related=["powertop", "hddtemp"], risk="low"),
            make_cmd("sensors-detect", "检测系统中的传感器芯片", "硬件/传感器与电源",
                     install_required=True, install_method="随 lm-sensors 安装",
                     options=["--auto 自动模式", "--interactive 交互模式"],
                     examples=[["sudo sensors-detect --auto", "自动检测传感器"]],
                     related=["sensors", "dmidecode"], risk="medium", risk_desc="自动检测会加载内核模块，请确认系统兼容性"),
            make_cmd("powertop", "电源消耗与节能诊断", "硬件/传感器与电源",
                     install_required=True, install_method="包管理器安装，如 sudo apt install powertop",
                     options=["--calibrate 校准", "--html 生成报告", "--auto-tune 自动调优"],
                     examples=[["powertop", "交互式电源分析"], ["sudo powertop --auto-tune", "自动优化电源"]],
                     related=["tlp", "sensors"], risk="medium", risk_desc="--auto-tune 会修改设备省电设置，可能影响性能或外设"),
            make_cmd("tlp", "Linux 笔记本电源管理", "硬件/传感器与电源",
                     usage="tlp [COMMAND]",
                     install_required=True, install_method="包管理器安装，如 sudo apt install tlp",
                     options=["start 启动", "stat 状态", "bat 电池模式", "ac 电源模式"],
                     examples=[["sudo tlp start", "启动 TLP"], ["sudo tlp bat", "切换到电池模式"]],
                     related=["powertop", "thermald"], risk="medium", risk_desc="电源配置错误可能导致性能下降或 USB 掉线"),
            make_cmd("thermald", "Intel 平台热量管理守护进程", "硬件/传感器与电源",
                     options=["--no-daemon", "--dbus-enable", "--config-file"],
                     examples=[["sudo thermald --no-daemon", "前台启动"], ["sudo systemctl start thermald", "系统服务启动"]],
                     related=["tlp", "sensors"], risk="medium", risk_desc="thermald 会主动调节 CPU，配置错误可能导致降频"),
            make_cmd("hddtemp", "显示硬盘温度", "硬件/传感器与电源",
                     install_required=True, install_method="包管理器安装，如 sudo apt install hddtemp",
                     options=["-u 单位", "-n 数值输出", "-d 守护进程"],
                     examples=[["sudo hddtemp /dev/sda", "查看 sda 温度"], ["hddtemp -n /dev/sda", "只输出温度值"]],
                     related=["smartctl", "sensors"], risk="low"),
        ],
    },
    "hardware/network.yaml": {
        "category": "硬件/网络硬件",
        "description": "网卡、无线、蓝牙等硬件管理",
        "commands": [
            make_cmd("ethtool", "查看和设置网卡参数", "硬件/网络硬件",
                     usage="ethtool [OPTIONS] INTERFACE",
                     install_required=True, install_method="多数 Linux 预装或包管理器安装",
                     options=["-i 驱动信息", "-S 统计", "-s 设置", "-a 查看 PAUSE"],
                     examples=[["ethtool eth0", "查看 eth0 信息"], ["sudo ethtool -s eth0 speed 1000 duplex full", "设置速率和双工"]],
                     related=["ip", "iw"], risk="medium", risk_desc="修改网卡参数可能断开网络，远程操作时谨慎"),
            make_cmd("iw", "新一代无线设备配置工具", "硬件/网络硬件",
                     usage="iw [OPTIONS] COMMAND",
                     install_required=True, install_method="多数 Linux 预装或包管理器安装",
                     options=["dev 设备", "list 列出", "scan 扫描", "connect 连接", "set 设置"],
                     examples=[["iw dev", "列出无线设备"], ["sudo iw dev wlan0 scan", "扫描 WiFi"]],
                     related=["iwconfig", "nmcli"], risk="medium", risk_desc="iw 可直接修改无线接口，请确认操作对象"),
            make_cmd("iwconfig", "传统无线接口配置", "硬件/网络硬件",
                     usage="iwconfig [INTERFACE] [OPTIONS]",
                     options=["essid 设置 SSID", "mode 模式", "key 密钥", "ap 接入点"],
                     examples=[["iwconfig", "查看无线配置"], ["sudo iwconfig wlan0 essid MyWiFi key s:mypassword", "连接 WiFi"]],
                     related=["iw", "nmcli"], risk="medium", risk_desc="命令行输入 WiFi 密钥会留在历史记录"),
            make_cmd("rfkill", "无线设备软开关管理", "硬件/网络硬件",
                     usage="rfkill [OPTIONS] COMMAND",
                     install_required=True, install_method="多数 Linux 预装",
                     options=["list 列出", "block 禁用", "unblock 启用", "event 事件"],
                     examples=[["rfkill list", "列出无线设备状态"], ["sudo rfkill unblock wifi", "启用 WiFi"]],
                     related=["iw", "bluetoothctl"], risk="low"),
            make_cmd("bluetoothctl", "蓝牙设备管理交互式工具", "硬件/网络硬件",
                     usage="bluetoothctl [OPTIONS] [COMMAND]",
                     install_required=True, install_method="随 bluez 安装",
                     options=["scan on 启用蓝牙扫描", "pair 配对设备", "connect 连接设备", "trust 信任设备", "remove 删除设备"],
                     examples=[["bluetoothctl scan on", "扫描蓝牙设备"], ["bluetoothctl pair 00:11:22:33:44:55", "配对设备"]],
                     related=["rfkill", "hciconfig"], risk="low"),
        ],
    },
    "hardware/storage.yaml": {
        "category": "硬件/存储与RAID",
        "description": "硬盘健康、NVMe、RAID、存储性能测试",
        "commands": [
            make_cmd("smartctl", "SMART 硬盘健康检测", "硬件/存储与RAID",
                     usage="smartctl [OPTIONS] DEVICE",
                     install_required=True, install_method="包管理器安装 smartmontools",
                     options=["-a 全部信息", "-H 健康状态", "-t short|long 自检", "-l error 错误日志"],
                     examples=[["sudo smartctl -a /dev/sda", "查看 sda 全部 SMART"], ["sudo smartctl -H /dev/sda", "快速健康检查"]],
                     related=["hdparm", "nvme"], risk="low"),
            make_cmd("nvme", "NVMe 设备管理 CLI", "硬件/存储与RAID",
                     usage="nvme [OPTIONS] COMMAND",
                     install_required=True, install_method="包管理器安装 nvme-cli",
                     options=["list 列出设备", "smart-log 智能日志", "format 格式化", "fw-log"],
                     examples=[["sudo nvme list", "列出 NVMe 设备"], ["sudo nvme smart-log /dev/nvme0", "查看 SMART 日志"]],
                     related=["smartctl", "fio"], risk="high", risk_desc="format 会清除所有数据，请确认目标设备"),
            make_cmd("mdadm", "Linux 软 RAID 管理", "硬件/存储与RAID",
                     usage="mdadm [OPTIONS] MODE DEVICE",
                     install_required=True, install_method="多数 Linux 预装或包管理器安装",
                     options=["--create 创建", "--assemble 组装", "--detail 详情", "--stop 停止", "--manage 管理"],
                     examples=[["sudo mdadm --detail /dev/md0", "查看 RAID 详情"], ["sudo mdadm --create /dev/md0 --level=1 --raid-devices=2 /dev/sdb /dev/sdc", "创建 RAID1"]],
                     related=["lvm", "smartctl"], risk="critical", risk_desc="创建/停止 RAID 会擦除或暴露数据，请备份并确认设备"),
            make_cmd("lsscsi", "列出 SCSI/SAS 设备", "硬件/存储与RAID",
                     options=["-v 详细", "-l 长格式", "-g 显示 sg 设备"],
                     examples=[["lsscsi", "列出 SCSI 设备"], ["lsscsi -l", "长格式输出"]],
                     related=["sg_scan", "lsblk"], risk="low"),
            make_cmd("sg_scan", "扫描 SCSI 通用设备", "硬件/存储与RAID",
                     options=["-i 查询", "-s 同步"],
                     examples=[["sg_scan", "扫描 sg 设备"], ["sg_scan -i", "查询设备信息"]],
                     related=["lsscsi", "smartctl"], risk="low"),
            make_cmd("partprobe", "通知内核分区表变化", "硬件/存储与RAID",
                     usage="partprobe [OPTIONS] [DEVICE]",
                     options=["-d 不更新", "-s 显示摘要"],
                     examples=[["sudo partprobe", "通知所有设备"], ["sudo partprobe /dev/sdb", "通知 sdb"]],
                     related=["parted", "fdisk"], risk="medium", risk_desc="分区表变更可能影响已挂载文件系统，请确认无冲突"),
            make_cmd("fio", "灵活的 I/O 测试器", "硬件/存储与RAID",
                     usage="fio [OPTIONS] [JOB FILE]",
                     install_required=True, install_method="包管理器安装，如 sudo apt install fio",
                     options=["--name", "--filename", "--rw", "--bs", "--size", "--numjobs"],
                     examples=[["fio --name=test --filename=/tmp/test --rw=randread --bs=4k --size=1G", "随机读测试"], ["fio job.fio", "执行 job 文件"]],
                     related=["bonnie++", "iostat"], risk="high", risk_desc="fio 会写入大量数据并占用 IO，请确认目标磁盘和文件系统"),
            make_cmd("bonnie++", "文件系统性能基准测试", "硬件/存储与RAID",
                     usage="bonnie++ [OPTIONS]",
                     install_required=True, install_method="包管理器安装，如 sudo apt install bonnie++",
                     options=["-d 测试目录", "-u 用户", "-r 内存大小", "-s 文件大小"],
                     examples=[["bonnie++ -d /tmp -u root", "测试 /tmp"], ["bonnie++ -f -n 0 -r 4096 -d /mnt", "简化测试"]],
                     related=["fio", "hdparm"], risk="high", risk_desc="会创建大文件并大量读写，请确认目录空间和权限"),
        ],
    },
    "hardware/gpu.yaml": {
        "category": "硬件/GPU与加速器",
        "description": "NVIDIA、AMD、Intel GPU 与 OpenCL 设备管理",
        "commands": [
            make_cmd("nvidia-smi", "NVIDIA GPU 管理与监控", "硬件/GPU与加速器",
                     usage="nvidia-smi [OPTIONS]",
                     install_required=True, install_method="随 NVIDIA 驱动安装",
                     options=["-L 列出 GPU", "-q 查询", "-dmon 监控", "-pl 设置功耗限制", "-i 指定 GPU"],
                     examples=[["nvidia-smi", "显示 GPU 状态"], ["nvidia-smi dmon -s pucm", "监控功耗/温度/显存"]],
                     related=["nvtop", "rocm-smi"], risk="medium", risk_desc="修改功耗/频率限制可能影响稳定性或硬件寿命"),
            make_cmd("rocm-smi", "AMD ROCm GPU 管理", "硬件/GPU与加速器",
                     usage="rocm-smi [OPTIONS]",
                     install_required=True, install_method="随 AMD ROCm 安装",
                     options=["--showproductname", "--showclock", "--setfan", "--setperflevel"],
                     examples=[["rocm-smi", "显示 AMD GPU 状态"], ["rocm-smi --showproductname", "显示产品名"]],
                     related=["nvidia-smi", "radeontop"], risk="medium", risk_desc="修改风扇或性能等级需谨慎"),
            make_cmd("intel-gpu-top", "Intel GPU 占用监控", "硬件/GPU与加速器",
                     install_required=True, install_method="包管理器安装 intel-gpu-tools",
                     options=["-s 采样", "-o 输出文件"],
                     examples=[["sudo intel-gpu-top", "实时监控 Intel GPU"], ["sudo intel-gpu-top -s 1000", "每秒采样"]],
                     related=["radeontop", "nvidia-smi"], risk="low"),
            make_cmd("radeontop", "AMD GPU 占用监控", "硬件/GPU与加速器",
                     install_required=True, install_method="包管理器安装，如 sudo apt install radeontop",
                     options=["-d 守护模式", "-s 采样", "-t 透明度"],
                     examples=[["sudo radeontop", "实时监控 AMD GPU"], ["sudo radeontop -d /tmp/radeontop.log", "记录到文件"]],
                     related=["rocm-smi", "intel-gpu-top"], risk="low"),
            make_cmd("clinfo", "显示 OpenCL 平台与设备信息", "硬件/GPU与加速器",
                     install_required=True, install_method="包管理器安装，如 sudo apt install clinfo",
                     options=["-l 简要", "-a 全部"],
                     examples=[["clinfo", "显示 OpenCL 信息"], ["clinfo -l", "简要列出平台设备"]],
                     related=["nvidia-smi", "rocm-smi"], risk="low"),
        ],
    },
    "hardware/perf.yaml": {
        "category": "硬件/性能与调度",
        "description": "CPU 调度、性能分析、 cgroup 与压力测试",
        "commands": [
            make_cmd("perf", "Linux 性能分析工具", "硬件/性能与调度",
                     usage="perf [OPTIONS] COMMAND",
                     install_required=True, install_method="linux-tools-common 包",
                     options=["top 实时热点", "record 记录", "report 报告", "stat 统计", "list 事件"],
                     examples=[["sudo perf top", "实时查看热点函数"], ["sudo perf record -g ./app && sudo perf report", "记录并分析"]],
                     related=["turbostat", "strace"], risk="low"),
            make_cmd("turbostat", "Intel CPU 频率与功耗监控", "硬件/性能与调度",
                     install_required=True, install_method="linux-tools-common 包",
                     options=["--show 显示列", "--interval", "--Summary"],
                     examples=[["sudo turbostat", "监控 CPU"], ["sudo turbostat --interval 1 --show Core,CPU,Avg_MHz,Busy%", "每秒显示核心频率"]],
                     related=["perf", "cpupower"], risk="low"),
            make_cmd("cpupower", "CPU 频率与空闲状态管理", "硬件/性能与调度",
                     usage="cpupower [OPTIONS] COMMAND",
                     install_required=True, install_method="linux-tools-common 包",
                     options=["frequency-info 频率信息", "frequency-set 设置频率", "idle-info 空闲状态", "set 策略"],
                     examples=[["cpupower frequency-info", "查看 CPU 频率策略"], ["sudo cpupower frequency-set -g performance", "设置为性能模式"]],
                     related=["turbostat", "perf"], risk="medium", risk_desc="强制设置频率策略可能影响功耗和散热"),
            make_cmd("taskset", "设置或查看进程 CPU 亲和性", "硬件/性能与调度",
                     usage="taskset [OPTIONS] [MASK | -c LIST] [COMMAND]",
                     options=["-c CPU 列表", "-p 修改现有 PID", "-a 所有线程"],
                     examples=[["taskset -c 0 ./app", "绑定到 CPU 0"], ["taskset -pc 0-3 1234", "修改 PID 1234 亲和性"]],
                     related=["numactl", "chrt"], risk="medium", risk_desc="错误的亲和性会降低性能或导致调度不均"),
            make_cmd("chrt", "设置实时调度策略", "硬件/性能与调度",
                     usage="chrt [OPTIONS] [PRIO] [COMMAND]",
                     options=["-f FIFO", "-r RR", "-o OTHER", "-p 修改 PID"],
                     examples=[["sudo chrt -f 99 ./app", "以 FIFO 优先级 99 运行"], ["chrt -p 1234", "查看 PID 调度策略"]],
                     related=["nice", "taskset"], risk="high", risk_desc="实时调度可能饿死其他进程，需谨慎使用"),
            make_cmd("ionice", "设置进程 I/O 调度优先级", "硬件/性能与调度",
                     usage="ionice [OPTIONS] [COMMAND]",
                     options=["-c 类别", "-n 优先级", "-p 修改 PID"],
                     examples=[["ionice -c 3 -p 1234", "将 PID 设为 idle IO 类"], ["ionice -c 2 -n 0 ./backup", "高优先级 IO 运行"]],
                     related=["nice", "cgexec"], risk="low"),
            make_cmd("cset", "cpuset 资源隔离工具", "硬件/性能与调度",
                     usage="cset [SUBCOMMAND] [OPTIONS]",
                     install_required=True, install_method="包管理器安装 cpuset",
                     options=["set 创建 cpuset", "proc 移动进程", "shield 隔离 CPU"],
                     examples=[["sudo cset shield --cpu=2-3", "隔离 CPU 2-3"], ["sudo cset proc --move --pid=1234 --set=user", "移动进程到 user cpuset"]],
                     related=["taskset", "numactl"], risk="medium", risk_desc="cpuset 隔离错误会限制进程可用资源"),
            make_cmd("cgexec", "在指定 cgroup 中运行命令", "硬件/性能与调度",
                     usage="cgexec [OPTIONS] GROUP COMMAND",
                     install_required=True, install_method="随 cgroup-tools 安装",
                     options=["-g 控制器:路径", "-b 忽略 systemd"],
                     examples=[["sudo cgexec -g cpu,memory:mygroup ./app", "在 mygroup 中运行"], ["sudo cgexec -g cpuset:db python server.py", "限制数据库 CPU 集合"]],
                     related=["systemd-run", "cset"], risk="medium", risk_desc="cgroup 限制过严会导致 OOM 或 CPU 饥饿"),
            make_cmd("stress", "简单的系统压力测试", "硬件/性能与调度",
                     install_required=True, install_method="包管理器安装，如 sudo apt install stress",
                     options=["--cpu CPU 数", "--io IO 线程", "--vm 内存 workers", "--timeout"],
                     examples=[["stress --cpu 4 --timeout 60s", "CPU 压测 60 秒"], ["stress --vm 2 --vm-bytes 1G --timeout 60s", "内存压测"]],
                     related=["stress-ng", "s-tui"], risk="high", risk_desc="压测会消耗系统资源，可能导致响应变慢或 OOM"),
            make_cmd("stress-ng", "更全面的系统压力测试", "硬件/性能与调度",
                     install_required=True, install_method="包管理器安装，如 sudo apt install stress-ng",
                     options=["--cpu 8", "--disk 4", "--vm 4", "--timeout 60s", "--metrics-brief"],
                     examples=[["stress-ng --cpu 8 --timeout 60s --metrics-brief", "CPU 压测"], ["stress-ng --class io --sequential 4 --timeout 60s", "顺序 IO 压测"]],
                     related=["stress", "fio"], risk="high", risk_desc="stress-ng 有大量测试，错误使用会压垮系统"),
            make_cmd("s-tui", "终端 CPU 压力与监控 TUI", "硬件/性能与调度",
                     install_required=True, install_method="pip install s-tui 或包管理器",
                     options=["--no-mouse", "--csv", "--time"],
                     examples=[["s-tui", "启动交互式监控"], ["s-tui --csv stress.csv --time 300", "记录 300 秒数据"]],
                     related=["stress", "turbostat"], risk="medium", risk_desc="运行 stress 测试会提升温度和功耗，注意散热"),
        ],
    },
    "hardware/firmware.yaml": {
        "category": "硬件/固件与UEFI",
        "description": "BIOS/UEFI、固件更新、启动项管理",
        "commands": [
            make_cmd("fwupd", "Linux 固件更新守护进程与工具", "硬件/固件与UEFI",
                     usage="fwupdmgr [OPTIONS] COMMAND",
                     install_required=True, install_method="包管理器安装 fwupd",
                     options=["get-devices", "get-updates", "update", "refresh"],
                     examples=[["fwupdmgr get-devices", "列出可更新设备"], ["fwupdmgr update", "安装可用固件更新"]],
                     related=["efibootmgr", "flashrom"], risk="high", risk_desc="固件更新失败可能导致硬件变砖，请确保电源稳定"),
            make_cmd("efibootmgr", "管理 UEFI 启动项", "硬件/固件与UEFI",
                     usage="efibootmgr [OPTIONS]",
                     install_required=True, install_method="多数 Linux 预装或 efibootmgr 包",
                     options=["-v 详细", "-c 创建", "-b 指定条目", "-B 删除", "-n 设置下次启动"],
                     examples=[["efibootmgr -v", "列出启动项"], ["sudo efibootmgr -c -d /dev/sda -p 1 -l '\\EFI\\ubuntu\\grubx64.efi' -L Ubuntu", "添加启动项"]],
                     related=["efivar", "grub-install"], risk="critical", risk_desc="删除或修改错误的启动项会导致系统无法启动"),
            make_cmd("efivar", "读取和写入 UEFI 变量", "硬件/固件与UEFI",
                     usage="efivar [OPTIONS] [NAME]",
                     options=["-l 列出", "-p 打印", "-a 追加", "-f 文件"],
                     examples=[["efivar -l", "列出 UEFI 变量"], ["efivar -p -n BootOrder", "打印启动顺序"]],
                     related=["efibootmgr", "mokutil"], risk="high", risk_desc="修改 UEFI 变量可能导致启动失败或安全策略变更"),
            make_cmd("mokutil", "管理 UEFI Secure Boot MOK", "硬件/固件与UEFI",
                     install_required=True, install_method="包管理器安装 mokutil",
                     options=["--sb-state", "--list-enrolled", "--import", "--delete"],
                     examples=[["mokutil --sb-state", "查看 Secure Boot 状态"], ["sudo mokutil --import MOK.der", "导入 MOK"]],
                     related=["efibootmgr", "fwupd"], risk="high", risk_desc="错误的 MOK 管理可能导致驱动无法加载或安全策略破坏"),
            make_cmd("flashrom", "读取/写入/擦除闪存芯片", "硬件/固件与UEFI",
                     usage="flashrom [OPTIONS]",
                     install_required=True, install_method="包管理器安装 flashrom",
                     options=["-r 读取", "-w 写入", "-v 校验", "-p 编程器"],
                     examples=[["flashrom -p internal -r backup.rom", "备份主板 BIOS"], ["flashrom -p internal -w new.rom", "刷写 BIOS"]],
                     related=["fwupd", "dmidecode"], risk="critical", risk_desc="刷写 BIOS 失败可能导致主板变砖，请谨慎"),
            make_cmd("biosdecode", "解析 BIOS 信息", "硬件/固件与UEFI",
                     options=["-d 转储", "-h 帮助"],
                     examples=[["biosdecode", "解析 BIOS"], ["sudo biosdecode", "以 root 解析 BIOS"]],
                     related=["dmidecode", "vpddecode"], risk="low"),
            make_cmd("vpddecode", "解析 VPD（重要产品数据）", "硬件/固件与UEFI",
                     options=["-s 只显示系统", "-b 只显示 baseboard"],
                     examples=[["vpddecode", "显示 VPD"], ["sudo vpddecode", "以 root 解析 VPD"]],
                     related=["dmidecode", "biosdecode"], risk="low"),
        ],
    },
    "hardware/ipmi.yaml": {
        "category": "硬件/远程带外管理",
        "description": "IPMI 与 Redfish 远程硬件管理",
        "commands": [
            make_cmd("ipmitool", "IPMI 带外管理工具", "硬件/远程带外管理",
                     usage="ipmitool [OPTIONS] COMMAND",
                     install_required=True, install_method="包管理器安装，如 sudo apt install ipmitool",
                     options=["-I 接口", "-H 主机", "-U 用户", "-P 密码", "chassis status", "sol activate"],
                     examples=[["ipmitool -I lanplus -H 192.168.1.100 -U admin -P pass chassis status", "查看 chassis 状态"], ["ipmitool -H 192.168.1.100 -U admin -I lanplus sol activate", "启动 SOL 控制台"]],
                     related=["ipmicfg", "redfish"], risk="high", risk_desc="IPMI 可远程开关机、重置，请保护好凭据"),
            make_cmd("ipmicfg", "Supermicro IPMI 配置工具", "硬件/远程带外管理",
                     install_required=True, install_method="参考 Supermicro 官方工具",
                     options=["-m 设置 IP", "-k 设置子网掩码", "-g 设置网关", "-r 重置"],
                     examples=[["ipmicfg -m 192.168.1.50", "设置 BMC IP"], ["ipmicfg -r", "重置 BMC"]],
                     related=["ipmitool", "redfish"], risk="high", risk_desc="重置 BMC 会中断带外管理，请谨慎"),
            make_cmd("redfish", "Redfish API 客户端（python-redfish 或 curl 示例）", "硬件/远程带外管理",
                     usage="redfish [OPTIONS]",
                     install_required=True, install_method="pip install redfish 或参考厂商工具",
                     options=["--user", "--password", "--rhost", "--ServiceRoot"],
                     examples=[["curl -u admin:pass https://bmc/redfish/v1/Systems", "查询系统信息"], ["python -m redfish --rhost bmc --user admin --password pass Systems", "使用 python-redfish"]],
                     related=["ipmitool", "curl"], risk="medium", risk_desc="Redfish 可执行电源操作，请保护好凭据"),
        ],
    },
    "hardware/embedded.yaml": {
        "category": "硬件/嵌入式与IoT",
        "description": "单片机烧录、串口、I2C、GPIO 等嵌入式工具",
        "commands": [
            make_cmd("esptool", "ESP8266/ESP32 烧录工具", "硬件/嵌入式与IoT",
                     usage="esptool.py [OPTIONS] COMMAND",
                     install_required=True, install_method="pip install esptool",
                     options=["--port 串口", "--baud 波特率", "flash_id", "erase_flash", "write_flash"],
                     examples=[["esptool.py --port /dev/ttyUSB0 flash_id", "读取 Flash ID"], ["esptool.py --port /dev/ttyUSB0 write_flash 0x0 firmware.bin", "烧录固件"]],
                     related=["minicom", "dfu-util"], risk="medium", risk_desc="擦除/烧写 Flash 会清空设备，请确认端口和地址"),
            make_cmd("avrdude", "AVR 单片机烧录", "硬件/嵌入式与IoT",
                     usage="avrdude [OPTIONS]",
                     install_required=True, install_method="包管理器安装，如 sudo apt install avrdude",
                     options=["-p 芯片", "-c 编程器", "-P 端口", "-U memop", "-b 波特率"],
                     examples=[["avrdude -p m328p -c usbasp -U flash:r:backup.hex:i", "读取 Flash"], ["avrdude -p m328p -c usbasp -U flash:w:firmware.hex:i", "写入 Flash"]],
                     related=["esptool", "openocd"], risk="medium", risk_desc="错误的熔丝位设置会锁死芯片"),
            make_cmd("openocd", "开源片上调试器", "硬件/嵌入式与IoT",
                     usage="openocd [OPTIONS]",
                     install_required=True, install_method="包管理器安装，如 sudo apt install openocd",
                     options=["-f 配置文件", "-c 命令", "-d 调试级别"],
                     examples=[["openocd -f interface/stlink.cfg -f target/stm32f4x.cfg", "连接 STM32"], ["openocd -f interface/stlink.cfg -c 'program firmware.bin verify reset exit'", "烧录"]],
                     related=["st-flash", "avrdude"], risk="medium", risk_desc="调试操作可读写内存，请确认目标设备"),
            make_cmd("st-flash", "STM32 ST-Link 烧录工具", "硬件/嵌入式与IoT",
                     install_required=True, install_method="参考 https://github.com/stlink-org/stlink",
                     options=["write 写入", "read 读取", "erase 擦除", "reset"],
                     examples=[["st-flash write firmware.bin 0x8000000", "烧录到 Flash 起始地址"], ["st-flash erase", "擦除芯片"]],
                     related=["openocd", "dfu-util"], risk="medium", risk_desc="擦除会清空 Flash"),
            make_cmd("dfu-util", "USB DFU 设备固件更新", "硬件/嵌入式与IoT",
                     install_required=True, install_method="包管理器安装，如 sudo apt install dfu-util",
                     options=["-l 列出", "-D 下载固件", "-U 上传", "-a 接口"],
                     examples=[["dfu-util -l", "列出 DFU 设备"], ["dfu-util -a 0 -D firmware.dfu", "下载固件"]],
                     related=["esptool", "st-flash"], risk="medium", risk_desc="固件更新失败可能使设备无法启动"),
            make_cmd("minicom", "串口通信终端", "硬件/嵌入式与IoT",
                     install_required=True, install_method="包管理器安装，如 sudo apt install minicom",
                     options=["-D 设备", "-b 波特率", "-C 捕获日志", "-s 配置"],
                     examples=[["minicom -D /dev/ttyUSB0 -b 115200", "连接串口"], ["minicom -C capture.log -D /dev/ttyUSB0", "记录日志"]],
                     related=["picocom", "screen"], risk="low"),
            make_cmd("picocom", "极简串口终端", "硬件/嵌入式与IoT",
                     install_required=True, install_method="包管理器安装，如 sudo apt install picocom",
                     options=["--baud 波特率", "--flow 流控", "--imap", "--omap"],
                     examples=[["picocom -b 115200 /dev/ttyUSB0", "连接串口"], ["picocom --echo -b 9600 /dev/ttyUSB0", "回显模式"]],
                     related=["minicom", "screen"], risk="low"),
            make_cmd("i2cdetect", "扫描 I2C 总线上的设备", "硬件/嵌入式与IoT",
                     usage="i2cdetect [OPTIONS] BUS",
                     install_required=True, install_method="包管理器安装 i2c-tools",
                     options=["-y 自动 yes", "-r 读扫描", "-q 快速扫描", "-a 扫描全部地址"],
                     examples=[["sudo i2cdetect -y 1", "扫描 I2C-1"], ["sudo i2cdetect -l", "列出 I2C 总线"]],
                     related=["i2cget", "i2cset"], risk="low"),
            make_cmd("i2cget", "读取 I2C 设备寄存器", "硬件/嵌入式与IoT",
                     usage="i2cget [OPTIONS] BUS CHIP-ADDRESS DATA-ADDRESS",
                     install_required=True, install_method="随 i2c-tools 安装",
                     options=["-y 自动 yes", "-f 强制访问"],
                     examples=[["sudo i2cget -y 1 0x50 0x00", "读取 I2C 设备 0x50 的 0x00 寄存器"]],
                     related=["i2cset", "i2cdetect"], risk="low"),
            make_cmd("i2cset", "写入 I2C 设备寄存器", "硬件/嵌入式与IoT",
                     usage="i2cset [OPTIONS] BUS CHIP-ADDRESS DATA-ADDRESS VALUE",
                     install_required=True, install_method="随 i2c-tools 安装",
                     options=["-y 自动 yes", "-m 掩码"],
                     examples=[["sudo i2cset -y 1 0x50 0x00 0xFF", "写入 0xFF 到寄存器"]],
                     related=["i2cget", "i2cdetect"], risk="medium", risk_desc="错误写入可能损坏 I2C 设备配置"),
            make_cmd("gpio", "Linux GPIO 命令行工具（libgpiod）", "硬件/嵌入式与IoT",
                     usage="gpio [OPTIONS] COMMAND",
                     install_required=True, install_method="包管理器安装 gpiod",
                     options=["info 信息", "get 读取", "set 设置", "find 查找"],
                     examples=[["gpioinfo", "列出 GPIO 线和芯片"], ["gpioset gpiochip0 25=1", "设置 GPIO 25 为高"]],
                     related=["i2cset", "raspi-gpio"], risk="medium", risk_desc="GPIO 控制硬件，错误电平可能损坏外设"),
            make_cmd("raspi-gpio", "树莓派 GPIO 工具", "硬件/嵌入式与IoT",
                     install_required=True, install_method="Raspberry Pi OS 预装",
                     options=["get 读取", "set 设置", "func 功能"],
                     examples=[["raspi-gpio get 25", "读取 GPIO 25"], ["raspi-gpio set 25 op dh", "设置 GPIO25 输出高"]],
                     related=["gpio", "i2cset"], risk="medium", risk_desc="同样需要注意外设电平保护"),
        ],
    },
    "lang/more.yaml": {
        "category": "编程语言/扩展工具链",
        "description": "Rust、PHP、Ruby、.NET、Scala、Kotlin、Groovy 等语言工具链",
        "commands": [
            make_cmd("cargo", "Rust 构建与包管理器", "编程语言/扩展工具链",
                     usage="cargo [OPTIONS] COMMAND",
                     install_required=True, install_method="参考 https://www.rust-lang.org/tools/install",
                     options=["build 构建", "run 运行", "test 测试", "publish 发布", "clippy 静态检查"],
                     examples=[["cargo build --release", "发布构建"], ["cargo test", "运行测试"]],
                     related=["rustc", "rustup"], risk="low"),
            make_cmd("rustup", "Rust 工具链管理器", "编程语言/扩展工具链",
                     install_required=True, install_method="参考 https://rustup.rs/",
                     options=["toolchain 管理工具链", "target 添加目标", "component 组件", "update 更新"],
                     examples=[["rustup update", "更新 Rust"], ["rustup target add wasm32-unknown-unknown", "添加 WASM 目标"]],
                     related=["cargo", "rustc"], risk="low"),
            make_cmd("php", "PHP 命令行解释器", "编程语言/扩展工具链",
                     usage="php [OPTIONS] [FILE]",
                     install_required=True, install_method="包管理器安装，如 sudo apt install php-cli",
                     options=["-r 运行代码", "-f 文件", "-S 内置服务器", "-l 语法检查"],
                     examples=[["php -r 'echo phpversion();'", "查看 PHP 版本"], ["php -S localhost:8000", "启动开发服务器"]],
                     related=["composer", "phpunit"], risk="low"),
            make_cmd("composer", "PHP 依赖管理器", "编程语言/扩展工具链",
                     install_required=True, install_method="参考 https://getcomposer.org/download/",
                     options=["install 安装依赖", "update 更新", "require 添加包", "autoload 生成"],
                     examples=[["composer install", "安装依赖"], ["composer require monolog/monolog", "添加包"]],
                     related=["php", "npm"], risk="low"),
            make_cmd("ruby", "Ruby 解释器", "编程语言/扩展工具链",
                     usage="ruby [OPTIONS] [FILE]",
                     install_required=True, install_method="包管理器安装或 rbenv",
                     options=["-e 执行代码", "-v 版本", "-I 加载路径"],
                     examples=[["ruby -e 'puts RUBY_VERSION'", "查看 Ruby 版本"], ["ruby script.rb", "运行脚本"]],
                     related=["gem", "bundle"], risk="low"),
            make_cmd("gem", "Ruby 包管理器", "编程语言/扩展工具链",
                     usage="gem [OPTIONS] COMMAND",
                     install_required=True, install_method="随 Ruby 安装",
                     options=["install 安装", "list 列出", "uninstall 卸载", "update"],
                     examples=[["gem install rails", "安装 Rails"], ["gem list", "列出已安装 gem"]],
                     related=["ruby", "bundle"], risk="low"),
            make_cmd("bundle", "Ruby 项目依赖管理", "编程语言/扩展工具链",
                     install_required=True, install_method="gem install bundler",
                     options=["install 安装", "update 更新", "exec 在 bundle 环境执行"],
                     examples=[["bundle install", "安装 Gemfile 依赖"], ["bundle exec rails s", "在 bundle 环境启动 Rails"]],
                     related=["gem", "ruby"], risk="low"),
            make_cmd("dotnet", ".NET 命令行工具", "编程语言/扩展工具链",
                     usage="dotnet [OPTIONS] COMMAND",
                     install_required=True, install_method="参考 https://dotnet.microsoft.com/download",
                     options=["new 创建项目", "build 构建", "run 运行", "publish 发布", "add package"],
                     examples=[["dotnet new console -o MyApp", "创建控制台项目"], ["dotnet build", "构建项目"]],
                     related=["nuget", "msbuild"], risk="low"),
            make_cmd("scala", "Scala 解释器与运行器", "编程语言/扩展工具链",
                     install_required=True, install_method="参考 https://www.scala-lang.org/download/",
                     options=["-version", "-cp 类路径", "-D 系统属性"],
                     examples=[["scala -version", "查看版本"], ["scala Hello.scala", "运行 Scala 脚本"]],
                     related=["sbt", "java"], risk="low"),
            make_cmd("sbt", "Scala 构建工具", "编程语言/扩展工具链",
                     install_required=True, install_method="参考 https://www.scala-sbt.org/download.html",
                     options=["compile", "test", "run", "assembly"],
                     examples=[["sbt compile", "编译"], ["sbt test", "运行测试"]],
                     related=["scala", "mvn"], risk="low"),
            make_cmd("kotlin", "Kotlin 命令行编译器", "编程语言/扩展工具链",
                     install_required=True, install_method="参考 https://kotlinlang.org/docs/command-line.html",
                     options=["-version", "-cp", "-d 输出"],
                     examples=[["kotlinc Hello.kt -include-runtime -d hello.jar", "编译为 jar"], ["kotlin hello.jar", "运行"]],
                     related=["java", "gradle"], risk="low"),
            make_cmd("groovy", "Groovy 脚本语言", "编程语言/扩展工具链",
                     install_required=True, install_method="SDKMAN 或包管理器安装",
                     options=["-v", "-e 执行", "-classpath"],
                     examples=[["groovy -v", "查看版本"], ["groovy script.groovy", "运行脚本"]],
                     related=["java", "gradle"], risk="low"),
        ],
    },
    "cicd/more.yaml": {
        "category": "CI/CD/扩展工具",
        "description": "Jenkins、GitLab、CircleCI、GitHub CLI 等 CI/CD 工具",
        "commands": [
            make_cmd("jenkins-cli", "Jenkins 命令行管理工具", "CI/CD/扩展工具",
                     usage="java -jar jenkins-cli.jar [OPTIONS] COMMAND",
                     install_required=True, install_method="从 Jenkins 管理页下载 jenkins-cli.jar",
                     options=["-s Jenkins URL", "-auth 认证", "who-am-i", "build 触发构建", "install-plugin"],
                     examples=[["java -jar jenkins-cli.jar -s http://jenkins:8080 who-am-i", "查看当前用户"], ["java -jar jenkins-cli.jar -s http://jenkins:8080 build myjob", "触发构建"]],
                     related=["gitlab-runner", "github-actions"], risk="medium", risk_desc="jenkins-cli 可安装插件和重启 Jenkins，请保护好凭据"),
            make_cmd("gitlab-runner", "GitLab CI 运行器", "CI/CD/扩展工具",
                     usage="gitlab-runner [OPTIONS] COMMAND",
                     install_required=True, install_method="参考 https://docs.gitlab.com/runner/install/",
                     options=["register 注册", "list", "run 单 runner", "unregister"],
                     examples=[["gitlab-runner register", "注册 runner"], ["gitlab-runner list", "列出 runner"]],
                     related=["jenkins-cli", "github-actions"], risk="medium", risk_desc="register 需要 GitLab token，请勿泄露"),
            make_cmd("circleci", "CircleCI CLI", "CI/CD/扩展工具",
                     install_required=True, install_method="参考 https://circleci.com/docs/local-cli/",
                     options=["config validate", "local execute", "orb"],
                     examples=[["circleci config validate", "验证 config.yml"], ["circleci local execute --job test", "本地执行 job"]],
                     related=["github-actions", "gitlab-runner"], risk="low"),
            make_cmd("gh", "GitHub 官方 CLI", "CI/CD/扩展工具",
                     install_required=True, install_method="参考 https://cli.github.com/",
                     options=["repo 仓库", "pr Pull Request", "issue", "workflow", "release"],
                     examples=[["gh pr create", "创建 PR"], ["gh workflow run ci.yml", "触发 workflow"]],
                     related=["git", "github-actions"], risk="low", risk_desc="gh 会操作远程仓库，请确认当前仓库和分支"),
        ],
    },
    "cloud/more.yaml": {
        "category": "云平台/多云CLI",
        "description": "GCP、Azure、DigitalOcean、Linode 等云平台 CLI",
        "commands": [
            make_cmd("gcloud", "Google Cloud 官方 CLI", "云平台/多云CLI",
                     usage="gcloud [OPTIONS] COMMAND",
                     install_required=True, install_method="参考 https://cloud.google.com/sdk/docs/install",
                     options=["config 配置", "compute 计算", "container 容器", "run 部署", "auth"],
                     examples=[["gcloud auth login", "登录"], ["gcloud compute instances list", "列出 VM"]],
                     related=["aws", "terraform"], risk="medium", risk_desc="gcloud 会创建/删除云资源并计费，请确认项目和区域"),
            make_cmd("az", "Azure 官方 CLI", "云平台/多云CLI",
                     usage="az [OPTIONS] COMMAND",
                     install_required=True, install_method="参考 https://learn.microsoft.com/cli/azure/install-azure-cli",
                     options=["login", "group", "vm", "aks", "account"],
                     examples=[["az login", "登录 Azure"], ["az vm list", "列出虚拟机"]],
                     related=["aws", "terraform"], risk="medium", risk_desc="az 操作会产生费用，请确认订阅和资源组"),
            make_cmd("doctl", "DigitalOcean 官方 CLI", "云平台/多云CLI",
                     install_required=True, install_method="参考 https://docs.digitalocean.com/reference/doctl/how-to/install/",
                     options=["auth init", "compute droplet", "kubernetes cluster", "apps"],
                     examples=[["doctl auth init", "初始化认证"], ["doctl compute droplet list", "列出 droplet"]],
                     related=["linode-cli", "aws"], risk="medium", risk_desc="droplet 操作会计费，请确认"),
            make_cmd("linode-cli", "Linode 官方 CLI", "云平台/多云CLI",
                     install_required=True, install_method="pip install linode-cli",
                     options=["linodes list", "volumes", "domains", "account"],
                     examples=[["linode-cli linodes list", "列出 Linode"], ["linode-cli linodes create --region us-east --type g6-standard-2", "创建实例"]],
                     related=["doctl", "aws"], risk="medium", risk_desc="创建实例会计费"),
            make_cmd("aws-vault", "AWS 凭据安全存储与切换工具", "云平台/多云CLI",
                     install_required=True, install_method="参考 https://github.com/99designs/aws-vault",
                     options=["add 添加 profile", "exec 执行命令", "list", "rotate"],
                     examples=[["aws-vault add myprofile", "添加凭据"], ["aws-vault exec myprofile -- aws s3 ls", "以指定 profile 执行 AWS 命令"]],
                     related=["aws", "aws-vault"], risk="low", risk_desc="aws-vault 保护凭据，但仍需妥善保管主密码"),
        ],
    },
    "diagnostic/more.yaml": {
        "category": "系统诊断/扩展工具",
        "description": "系统调用跟踪、eBPF、容器系统诊断工具",
        "commands": [
            make_cmd("strace", "跟踪系统调用", "系统诊断/扩展工具",
                     usage="strace [OPTIONS] COMMAND",
                     install_required=True, install_method="多数 Linux 预装",
                     options=["-e 过滤系统调用", "-f 跟踪子进程", "-o 输出文件", "-p 附加 PID", "-c 统计"],
                     examples=[["strace -c ls", "统计 ls 的系统调用"], ["strace -e openat,read -o trace.log ./app", "跟踪文件 IO"]],
                     related=["ltrace", "perf"], risk="low"),
            make_cmd("ltrace", "跟踪库函数调用", "系统诊断/扩展工具",
                     usage="ltrace [OPTIONS] COMMAND",
                     install_required=True, install_method="多数 Linux 预装或包管理器安装",
                     options=["-e 过滤函数", "-f 跟踪子进程", "-o 输出文件", "-p 附加 PID"],
                     examples=[["ltrace -e malloc,free ./app", "跟踪内存分配"], ["ltrace -p 1234", "附加到进程"]],
                     related=["strace", "perf"], risk="low"),
            make_cmd("sysdig", "系统级监控与故障排查", "系统诊断/扩展工具",
                     install_required=True, install_method="参考 https://github.com/draios/sysdig",
                     options=["-c 凿子", "-p 输出格式", "-w 写入文件", "filter 过滤"],
                     examples=[["sudo sysdig", "实时监控系统调用"], ["sudo sysdig -c topprocs_cpu", "CPU 占用最高进程"]],
                     related=["bpftrace", "strace"], risk="medium", risk_desc="sysdig 会捕获系统调用，注意敏感数据"),
            make_cmd("bpftrace", "高级 eBPF 跟踪语言", "系统诊断/扩展工具",
                     install_required=True, install_method="参考 https://github.com/iovisor/bpftrace/blob/master/INSTALL.md",
                     options=["-e 程序", "-l 列出探针", "-p PID"],
                     examples=[["sudo bpftrace -e 'tracepoint:syscalls:sys_enter_openat { printf(\"%s %s\\n\", comm, str(args->filename)); }'", "跟踪 openat"], ["sudo bpftrace -l 'tracepoint:syscalls:*'", "列出探针"]],
                     related=["bcc", "perf"], risk="medium", risk_desc="bpftrace 在内核运行，脚本错误可能影响性能"),
            make_cmd("bcc", "BPF Compiler Collection 工具集", "系统诊断/扩展工具",
                     install_required=True, install_method="参考 https://github.com/iovisor/bcc/blob/master/INSTALL.md",
                     options=["tools 目录脚本", "-p PID"],
                     examples=[["sudo /usr/share/bcc/tools/opensnoop", "监控文件打开"], ["sudo /usr/share/bcc/tools/biolatency", "块设备延迟"]],
                     related=["bpftrace", "perf"], risk="medium", risk_desc="bcc 工具在内核运行，注意对生产系统的影响"),
        ],
    },
}


def main() -> int:
    meta = yaml.load(open(META_PATH, "r", encoding="utf-8"))
    existing_names = set()
    for rel_file in meta["data_files"]:
        path = DATA_DIR / rel_file
        if not path.exists():
            continue
        doc = yaml.load(open(path, "r", encoding="utf-8"))
        for cmd in doc.get("commands", []):
            existing_names.add(cmd["name"])

    total_added = 0
    for rel_file, spec in BATCH.items():
        path = DATA_DIR / rel_file
        path.parent.mkdir(parents=True, exist_ok=True)
        commands = []
        skipped = []
        for cmd in spec["commands"]:
            if cmd["name"] in existing_names:
                skipped.append(cmd["name"])
                continue
            commands.append(cmd)
            existing_names.add(cmd["name"])
        if not commands:
            print(f"{rel_file}: all commands already exist, skipped")
            continue
        doc = {"category": spec["category"], "description": spec["description"], "commands": commands}
        with open(path, "w", encoding="utf-8") as f:
            yaml.dump(doc, f)
        cat_id = rel_file.replace("/", "_").replace("-", "_").replace(".", "_")
        meta["categories"][cat_id] = {
            "id": cat_id,
            "name": spec["category"],
            "description": spec["description"],
            "parent": "",
            "order": 400,
        }
        if rel_file not in meta["data_files"]:
            meta["data_files"].append(rel_file)
        print(f"{rel_file}: added {len(commands)}, skipped {len(skipped)}")
        total_added += len(commands)

    cmd_count = 0
    for rel_file in meta["data_files"]:
        doc = yaml.load(open(DATA_DIR / rel_file, "r", encoding="utf-8"))
        cmd_count += len(doc["commands"])
    meta["description"] = f"cmd4coder 命令行工具大全数据文件 - 覆盖 {len(meta['categories'])} 个分类, {cmd_count} 命令"

    with open(META_PATH, "w", encoding="utf-8") as f:
        yaml.dump(meta, f)
    print(f"\nTotal added: {total_added}, total commands: {cmd_count}, categories: {len(meta['categories'])}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
